//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CozyComfortClient.UserServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDetails", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class UserDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int UserIdField;
        
        private char UserTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactPersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        private int ProductionCapacityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LicenseNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebsiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public char UserType {
            get {
                return this.UserTypeField;
            }
            set {
                if ((this.UserTypeField.Equals(value) != true)) {
                    this.UserTypeField = value;
                    this.RaisePropertyChanged("UserType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ContactPerson {
            get {
                return this.ContactPersonField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactPersonField, value) != true)) {
                    this.ContactPersonField = value;
                    this.RaisePropertyChanged("ContactPerson");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ContactNumber {
            get {
                return this.ContactNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactNumberField, value) != true)) {
                    this.ContactNumberField = value;
                    this.RaisePropertyChanged("ContactNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int ProductionCapacity {
            get {
                return this.ProductionCapacityField;
            }
            set {
                if ((this.ProductionCapacityField.Equals(value) != true)) {
                    this.ProductionCapacityField = value;
                    this.RaisePropertyChanged("ProductionCapacity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string LicenseNumber {
            get {
                return this.LicenseNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.LicenseNumberField, value) != true)) {
                    this.LicenseNumberField = value;
                    this.RaisePropertyChanged("LicenseNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Website {
            get {
                return this.WebsiteField;
            }
            set {
                if ((object.ReferenceEquals(this.WebsiteField, value) != true)) {
                    this.WebsiteField = value;
                    this.RaisePropertyChanged("Website");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserServiceReference.UserServiceSoap")]
    public interface UserServiceSoap {
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        CozyComfortClient.UserServiceReference.LoginResponse Login(CozyComfortClient.UserServiceReference.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<CozyComfortClient.UserServiceReference.LoginResponse> LoginAsync(CozyComfortClient.UserServiceReference.LoginRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Register", ReplyAction="*")]
        CozyComfortClient.UserServiceReference.RegisterResponse Register(CozyComfortClient.UserServiceReference.RegisterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Register", ReplyAction="*")]
        System.Threading.Tasks.Task<CozyComfortClient.UserServiceReference.RegisterResponse> RegisterAsync(CozyComfortClient.UserServiceReference.RegisterRequest request);
        
        // CODEGEN: Generating message contract since element name GetUserDetailsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserDetails", ReplyAction="*")]
        CozyComfortClient.UserServiceReference.GetUserDetailsResponse GetUserDetails(CozyComfortClient.UserServiceReference.GetUserDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<CozyComfortClient.UserServiceReference.GetUserDetailsResponse> GetUserDetailsAsync(CozyComfortClient.UserServiceReference.GetUserDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name oldPassword from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdatePassword", ReplyAction="*")]
        CozyComfortClient.UserServiceReference.UpdatePasswordResponse UpdatePassword(CozyComfortClient.UserServiceReference.UpdatePasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdatePassword", ReplyAction="*")]
        System.Threading.Tasks.Task<CozyComfortClient.UserServiceReference.UpdatePasswordResponse> UpdatePasswordAsync(CozyComfortClient.UserServiceReference.UpdatePasswordRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.UserServiceReference.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(CozyComfortClient.UserServiceReference.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string email, string password) {
            this.email = email;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.UserServiceReference.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(CozyComfortClient.UserServiceReference.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(string LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Register", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.UserServiceReference.RegisterRequestBody Body;
        
        public RegisterRequest() {
        }
        
        public RegisterRequest(CozyComfortClient.UserServiceReference.RegisterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public char userType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public CozyComfortClient.UserServiceReference.UserDetails details;
        
        public RegisterRequestBody() {
        }
        
        public RegisterRequestBody(string email, string password, char userType, CozyComfortClient.UserServiceReference.UserDetails details) {
            this.email = email;
            this.password = password;
            this.userType = userType;
            this.details = details;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterResponse", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.UserServiceReference.RegisterResponseBody Body;
        
        public RegisterResponse() {
        }
        
        public RegisterResponse(CozyComfortClient.UserServiceReference.RegisterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RegisterResult;
        
        public RegisterResponseBody() {
        }
        
        public RegisterResponseBody(string RegisterResult) {
            this.RegisterResult = RegisterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserDetails", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.UserServiceReference.GetUserDetailsRequestBody Body;
        
        public GetUserDetailsRequest() {
        }
        
        public GetUserDetailsRequest(CozyComfortClient.UserServiceReference.GetUserDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public char userType;
        
        public GetUserDetailsRequestBody() {
        }
        
        public GetUserDetailsRequestBody(int userId, char userType) {
            this.userId = userId;
            this.userType = userType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.UserServiceReference.GetUserDetailsResponseBody Body;
        
        public GetUserDetailsResponse() {
        }
        
        public GetUserDetailsResponse(CozyComfortClient.UserServiceReference.GetUserDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CozyComfortClient.UserServiceReference.UserDetails GetUserDetailsResult;
        
        public GetUserDetailsResponseBody() {
        }
        
        public GetUserDetailsResponseBody(CozyComfortClient.UserServiceReference.UserDetails GetUserDetailsResult) {
            this.GetUserDetailsResult = GetUserDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdatePasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdatePassword", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.UserServiceReference.UpdatePasswordRequestBody Body;
        
        public UpdatePasswordRequest() {
        }
        
        public UpdatePasswordRequest(CozyComfortClient.UserServiceReference.UpdatePasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdatePasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string oldPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string newPassword;
        
        public UpdatePasswordRequestBody() {
        }
        
        public UpdatePasswordRequestBody(int userId, string oldPassword, string newPassword) {
            this.userId = userId;
            this.oldPassword = oldPassword;
            this.newPassword = newPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdatePasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdatePasswordResponse", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.UserServiceReference.UpdatePasswordResponseBody Body;
        
        public UpdatePasswordResponse() {
        }
        
        public UpdatePasswordResponse(CozyComfortClient.UserServiceReference.UpdatePasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdatePasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdatePasswordResult;
        
        public UpdatePasswordResponseBody() {
        }
        
        public UpdatePasswordResponseBody(string UpdatePasswordResult) {
            this.UpdatePasswordResult = UpdatePasswordResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserServiceSoapChannel : CozyComfortClient.UserServiceReference.UserServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceSoapClient : System.ServiceModel.ClientBase<CozyComfortClient.UserServiceReference.UserServiceSoap>, CozyComfortClient.UserServiceReference.UserServiceSoap {
        
        public UserServiceSoapClient() {
        }
        
        public UserServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CozyComfortClient.UserServiceReference.LoginResponse CozyComfortClient.UserServiceReference.UserServiceSoap.Login(CozyComfortClient.UserServiceReference.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public string Login(string email, string password) {
            CozyComfortClient.UserServiceReference.LoginRequest inValue = new CozyComfortClient.UserServiceReference.LoginRequest();
            inValue.Body = new CozyComfortClient.UserServiceReference.LoginRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            CozyComfortClient.UserServiceReference.LoginResponse retVal = ((CozyComfortClient.UserServiceReference.UserServiceSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CozyComfortClient.UserServiceReference.LoginResponse> CozyComfortClient.UserServiceReference.UserServiceSoap.LoginAsync(CozyComfortClient.UserServiceReference.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<CozyComfortClient.UserServiceReference.LoginResponse> LoginAsync(string email, string password) {
            CozyComfortClient.UserServiceReference.LoginRequest inValue = new CozyComfortClient.UserServiceReference.LoginRequest();
            inValue.Body = new CozyComfortClient.UserServiceReference.LoginRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            return ((CozyComfortClient.UserServiceReference.UserServiceSoap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CozyComfortClient.UserServiceReference.RegisterResponse CozyComfortClient.UserServiceReference.UserServiceSoap.Register(CozyComfortClient.UserServiceReference.RegisterRequest request) {
            return base.Channel.Register(request);
        }
        
        public string Register(string email, string password, char userType, CozyComfortClient.UserServiceReference.UserDetails details) {
            CozyComfortClient.UserServiceReference.RegisterRequest inValue = new CozyComfortClient.UserServiceReference.RegisterRequest();
            inValue.Body = new CozyComfortClient.UserServiceReference.RegisterRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            inValue.Body.userType = userType;
            inValue.Body.details = details;
            CozyComfortClient.UserServiceReference.RegisterResponse retVal = ((CozyComfortClient.UserServiceReference.UserServiceSoap)(this)).Register(inValue);
            return retVal.Body.RegisterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CozyComfortClient.UserServiceReference.RegisterResponse> CozyComfortClient.UserServiceReference.UserServiceSoap.RegisterAsync(CozyComfortClient.UserServiceReference.RegisterRequest request) {
            return base.Channel.RegisterAsync(request);
        }
        
        public System.Threading.Tasks.Task<CozyComfortClient.UserServiceReference.RegisterResponse> RegisterAsync(string email, string password, char userType, CozyComfortClient.UserServiceReference.UserDetails details) {
            CozyComfortClient.UserServiceReference.RegisterRequest inValue = new CozyComfortClient.UserServiceReference.RegisterRequest();
            inValue.Body = new CozyComfortClient.UserServiceReference.RegisterRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            inValue.Body.userType = userType;
            inValue.Body.details = details;
            return ((CozyComfortClient.UserServiceReference.UserServiceSoap)(this)).RegisterAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CozyComfortClient.UserServiceReference.GetUserDetailsResponse CozyComfortClient.UserServiceReference.UserServiceSoap.GetUserDetails(CozyComfortClient.UserServiceReference.GetUserDetailsRequest request) {
            return base.Channel.GetUserDetails(request);
        }
        
        public CozyComfortClient.UserServiceReference.UserDetails GetUserDetails(int userId, char userType) {
            CozyComfortClient.UserServiceReference.GetUserDetailsRequest inValue = new CozyComfortClient.UserServiceReference.GetUserDetailsRequest();
            inValue.Body = new CozyComfortClient.UserServiceReference.GetUserDetailsRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.userType = userType;
            CozyComfortClient.UserServiceReference.GetUserDetailsResponse retVal = ((CozyComfortClient.UserServiceReference.UserServiceSoap)(this)).GetUserDetails(inValue);
            return retVal.Body.GetUserDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CozyComfortClient.UserServiceReference.GetUserDetailsResponse> CozyComfortClient.UserServiceReference.UserServiceSoap.GetUserDetailsAsync(CozyComfortClient.UserServiceReference.GetUserDetailsRequest request) {
            return base.Channel.GetUserDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<CozyComfortClient.UserServiceReference.GetUserDetailsResponse> GetUserDetailsAsync(int userId, char userType) {
            CozyComfortClient.UserServiceReference.GetUserDetailsRequest inValue = new CozyComfortClient.UserServiceReference.GetUserDetailsRequest();
            inValue.Body = new CozyComfortClient.UserServiceReference.GetUserDetailsRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.userType = userType;
            return ((CozyComfortClient.UserServiceReference.UserServiceSoap)(this)).GetUserDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CozyComfortClient.UserServiceReference.UpdatePasswordResponse CozyComfortClient.UserServiceReference.UserServiceSoap.UpdatePassword(CozyComfortClient.UserServiceReference.UpdatePasswordRequest request) {
            return base.Channel.UpdatePassword(request);
        }
        
        public string UpdatePassword(int userId, string oldPassword, string newPassword) {
            CozyComfortClient.UserServiceReference.UpdatePasswordRequest inValue = new CozyComfortClient.UserServiceReference.UpdatePasswordRequest();
            inValue.Body = new CozyComfortClient.UserServiceReference.UpdatePasswordRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.oldPassword = oldPassword;
            inValue.Body.newPassword = newPassword;
            CozyComfortClient.UserServiceReference.UpdatePasswordResponse retVal = ((CozyComfortClient.UserServiceReference.UserServiceSoap)(this)).UpdatePassword(inValue);
            return retVal.Body.UpdatePasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CozyComfortClient.UserServiceReference.UpdatePasswordResponse> CozyComfortClient.UserServiceReference.UserServiceSoap.UpdatePasswordAsync(CozyComfortClient.UserServiceReference.UpdatePasswordRequest request) {
            return base.Channel.UpdatePasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<CozyComfortClient.UserServiceReference.UpdatePasswordResponse> UpdatePasswordAsync(int userId, string oldPassword, string newPassword) {
            CozyComfortClient.UserServiceReference.UpdatePasswordRequest inValue = new CozyComfortClient.UserServiceReference.UpdatePasswordRequest();
            inValue.Body = new CozyComfortClient.UserServiceReference.UpdatePasswordRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.oldPassword = oldPassword;
            inValue.Body.newPassword = newPassword;
            return ((CozyComfortClient.UserServiceReference.UserServiceSoap)(this)).UpdatePasswordAsync(inValue);
        }
    }
}
