//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CozyComfortClient.SellerServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Seller", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Seller : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int SellerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StoreNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StoreLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebsiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SellerId {
            get {
                return this.SellerIdField;
            }
            set {
                if ((this.SellerIdField.Equals(value) != true)) {
                    this.SellerIdField = value;
                    this.RaisePropertyChanged("SellerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StoreName {
            get {
                return this.StoreNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StoreNameField, value) != true)) {
                    this.StoreNameField = value;
                    this.RaisePropertyChanged("StoreName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ContactNumber {
            get {
                return this.ContactNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactNumberField, value) != true)) {
                    this.ContactNumberField = value;
                    this.RaisePropertyChanged("ContactNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string StoreLocation {
            get {
                return this.StoreLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.StoreLocationField, value) != true)) {
                    this.StoreLocationField = value;
                    this.RaisePropertyChanged("StoreLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Website {
            get {
                return this.WebsiteField;
            }
            set {
                if ((object.ReferenceEquals(this.WebsiteField, value) != true)) {
                    this.WebsiteField = value;
                    this.RaisePropertyChanged("Website");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SellerOperationResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SellerOperationResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        private int SellerIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int SellerId {
            get {
                return this.SellerIdField;
            }
            set {
                if ((this.SellerIdField.Equals(value) != true)) {
                    this.SellerIdField = value;
                    this.RaisePropertyChanged("SellerId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SellerServiceReference.SellerServiceSoap")]
    public interface SellerServiceSoap {
        
        // CODEGEN: Generating message contract since element name seller from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterSeller", ReplyAction="*")]
        CozyComfortClient.SellerServiceReference.RegisterSellerResponse RegisterSeller(CozyComfortClient.SellerServiceReference.RegisterSellerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterSeller", ReplyAction="*")]
        System.Threading.Tasks.Task<CozyComfortClient.SellerServiceReference.RegisterSellerResponse> RegisterSellerAsync(CozyComfortClient.SellerServiceReference.RegisterSellerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSellerIdByAppUserId", ReplyAction="*")]
        int GetSellerIdByAppUserId(int appUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSellerIdByAppUserId", ReplyAction="*")]
        System.Threading.Tasks.Task<int> GetSellerIdByAppUserIdAsync(int appUserId);
        
        // CODEGEN: Generating message contract since element name seller from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateSellerProfile", ReplyAction="*")]
        CozyComfortClient.SellerServiceReference.UpdateSellerProfileResponse UpdateSellerProfile(CozyComfortClient.SellerServiceReference.UpdateSellerProfileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateSellerProfile", ReplyAction="*")]
        System.Threading.Tasks.Task<CozyComfortClient.SellerServiceReference.UpdateSellerProfileResponse> UpdateSellerProfileAsync(CozyComfortClient.SellerServiceReference.UpdateSellerProfileRequest request);
        
        // CODEGEN: Generating message contract since element name GetSellerDetailsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSellerDetails", ReplyAction="*")]
        CozyComfortClient.SellerServiceReference.GetSellerDetailsResponse GetSellerDetails(CozyComfortClient.SellerServiceReference.GetSellerDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSellerDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<CozyComfortClient.SellerServiceReference.GetSellerDetailsResponse> GetSellerDetailsAsync(CozyComfortClient.SellerServiceReference.GetSellerDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllSellersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllSellers", ReplyAction="*")]
        CozyComfortClient.SellerServiceReference.GetAllSellersResponse GetAllSellers(CozyComfortClient.SellerServiceReference.GetAllSellersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllSellers", ReplyAction="*")]
        System.Threading.Tasks.Task<CozyComfortClient.SellerServiceReference.GetAllSellersResponse> GetAllSellersAsync(CozyComfortClient.SellerServiceReference.GetAllSellersRequest request);
        
        // CODEGEN: Generating message contract since element name DeleteSellerResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteSeller", ReplyAction="*")]
        CozyComfortClient.SellerServiceReference.DeleteSellerResponse DeleteSeller(CozyComfortClient.SellerServiceReference.DeleteSellerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteSeller", ReplyAction="*")]
        System.Threading.Tasks.Task<CozyComfortClient.SellerServiceReference.DeleteSellerResponse> DeleteSellerAsync(CozyComfortClient.SellerServiceReference.DeleteSellerRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterSellerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterSeller", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.SellerServiceReference.RegisterSellerRequestBody Body;
        
        public RegisterSellerRequest() {
        }
        
        public RegisterSellerRequest(CozyComfortClient.SellerServiceReference.RegisterSellerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterSellerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CozyComfortClient.SellerServiceReference.Seller seller;
        
        public RegisterSellerRequestBody() {
        }
        
        public RegisterSellerRequestBody(CozyComfortClient.SellerServiceReference.Seller seller) {
            this.seller = seller;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterSellerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterSellerResponse", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.SellerServiceReference.RegisterSellerResponseBody Body;
        
        public RegisterSellerResponse() {
        }
        
        public RegisterSellerResponse(CozyComfortClient.SellerServiceReference.RegisterSellerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterSellerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CozyComfortClient.SellerServiceReference.SellerOperationResult RegisterSellerResult;
        
        public RegisterSellerResponseBody() {
        }
        
        public RegisterSellerResponseBody(CozyComfortClient.SellerServiceReference.SellerOperationResult RegisterSellerResult) {
            this.RegisterSellerResult = RegisterSellerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateSellerProfileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateSellerProfile", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.SellerServiceReference.UpdateSellerProfileRequestBody Body;
        
        public UpdateSellerProfileRequest() {
        }
        
        public UpdateSellerProfileRequest(CozyComfortClient.SellerServiceReference.UpdateSellerProfileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateSellerProfileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CozyComfortClient.SellerServiceReference.Seller seller;
        
        public UpdateSellerProfileRequestBody() {
        }
        
        public UpdateSellerProfileRequestBody(CozyComfortClient.SellerServiceReference.Seller seller) {
            this.seller = seller;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateSellerProfileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateSellerProfileResponse", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.SellerServiceReference.UpdateSellerProfileResponseBody Body;
        
        public UpdateSellerProfileResponse() {
        }
        
        public UpdateSellerProfileResponse(CozyComfortClient.SellerServiceReference.UpdateSellerProfileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateSellerProfileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CozyComfortClient.SellerServiceReference.SellerOperationResult UpdateSellerProfileResult;
        
        public UpdateSellerProfileResponseBody() {
        }
        
        public UpdateSellerProfileResponseBody(CozyComfortClient.SellerServiceReference.SellerOperationResult UpdateSellerProfileResult) {
            this.UpdateSellerProfileResult = UpdateSellerProfileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSellerDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSellerDetails", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.SellerServiceReference.GetSellerDetailsRequestBody Body;
        
        public GetSellerDetailsRequest() {
        }
        
        public GetSellerDetailsRequest(CozyComfortClient.SellerServiceReference.GetSellerDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSellerDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int sellerId;
        
        public GetSellerDetailsRequestBody() {
        }
        
        public GetSellerDetailsRequestBody(int sellerId) {
            this.sellerId = sellerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSellerDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSellerDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.SellerServiceReference.GetSellerDetailsResponseBody Body;
        
        public GetSellerDetailsResponse() {
        }
        
        public GetSellerDetailsResponse(CozyComfortClient.SellerServiceReference.GetSellerDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSellerDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CozyComfortClient.SellerServiceReference.Seller GetSellerDetailsResult;
        
        public GetSellerDetailsResponseBody() {
        }
        
        public GetSellerDetailsResponseBody(CozyComfortClient.SellerServiceReference.Seller GetSellerDetailsResult) {
            this.GetSellerDetailsResult = GetSellerDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllSellersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllSellers", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.SellerServiceReference.GetAllSellersRequestBody Body;
        
        public GetAllSellersRequest() {
        }
        
        public GetAllSellersRequest(CozyComfortClient.SellerServiceReference.GetAllSellersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllSellersRequestBody {
        
        public GetAllSellersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllSellersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllSellersResponse", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.SellerServiceReference.GetAllSellersResponseBody Body;
        
        public GetAllSellersResponse() {
        }
        
        public GetAllSellersResponse(CozyComfortClient.SellerServiceReference.GetAllSellersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllSellersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CozyComfortClient.SellerServiceReference.Seller[] GetAllSellersResult;
        
        public GetAllSellersResponseBody() {
        }
        
        public GetAllSellersResponseBody(CozyComfortClient.SellerServiceReference.Seller[] GetAllSellersResult) {
            this.GetAllSellersResult = GetAllSellersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteSellerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteSeller", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.SellerServiceReference.DeleteSellerRequestBody Body;
        
        public DeleteSellerRequest() {
        }
        
        public DeleteSellerRequest(CozyComfortClient.SellerServiceReference.DeleteSellerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteSellerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int sellerId;
        
        public DeleteSellerRequestBody() {
        }
        
        public DeleteSellerRequestBody(int sellerId) {
            this.sellerId = sellerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteSellerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteSellerResponse", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.SellerServiceReference.DeleteSellerResponseBody Body;
        
        public DeleteSellerResponse() {
        }
        
        public DeleteSellerResponse(CozyComfortClient.SellerServiceReference.DeleteSellerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteSellerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CozyComfortClient.SellerServiceReference.SellerOperationResult DeleteSellerResult;
        
        public DeleteSellerResponseBody() {
        }
        
        public DeleteSellerResponseBody(CozyComfortClient.SellerServiceReference.SellerOperationResult DeleteSellerResult) {
            this.DeleteSellerResult = DeleteSellerResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SellerServiceSoapChannel : CozyComfortClient.SellerServiceReference.SellerServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SellerServiceSoapClient : System.ServiceModel.ClientBase<CozyComfortClient.SellerServiceReference.SellerServiceSoap>, CozyComfortClient.SellerServiceReference.SellerServiceSoap {
        
        public SellerServiceSoapClient() {
        }
        
        public SellerServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SellerServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SellerServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SellerServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CozyComfortClient.SellerServiceReference.RegisterSellerResponse CozyComfortClient.SellerServiceReference.SellerServiceSoap.RegisterSeller(CozyComfortClient.SellerServiceReference.RegisterSellerRequest request) {
            return base.Channel.RegisterSeller(request);
        }
        
        public CozyComfortClient.SellerServiceReference.SellerOperationResult RegisterSeller(CozyComfortClient.SellerServiceReference.Seller seller) {
            CozyComfortClient.SellerServiceReference.RegisterSellerRequest inValue = new CozyComfortClient.SellerServiceReference.RegisterSellerRequest();
            inValue.Body = new CozyComfortClient.SellerServiceReference.RegisterSellerRequestBody();
            inValue.Body.seller = seller;
            CozyComfortClient.SellerServiceReference.RegisterSellerResponse retVal = ((CozyComfortClient.SellerServiceReference.SellerServiceSoap)(this)).RegisterSeller(inValue);
            return retVal.Body.RegisterSellerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CozyComfortClient.SellerServiceReference.RegisterSellerResponse> CozyComfortClient.SellerServiceReference.SellerServiceSoap.RegisterSellerAsync(CozyComfortClient.SellerServiceReference.RegisterSellerRequest request) {
            return base.Channel.RegisterSellerAsync(request);
        }
        
        public System.Threading.Tasks.Task<CozyComfortClient.SellerServiceReference.RegisterSellerResponse> RegisterSellerAsync(CozyComfortClient.SellerServiceReference.Seller seller) {
            CozyComfortClient.SellerServiceReference.RegisterSellerRequest inValue = new CozyComfortClient.SellerServiceReference.RegisterSellerRequest();
            inValue.Body = new CozyComfortClient.SellerServiceReference.RegisterSellerRequestBody();
            inValue.Body.seller = seller;
            return ((CozyComfortClient.SellerServiceReference.SellerServiceSoap)(this)).RegisterSellerAsync(inValue);
        }
        
        public int GetSellerIdByAppUserId(int appUserId) {
            return base.Channel.GetSellerIdByAppUserId(appUserId);
        }
        
        public System.Threading.Tasks.Task<int> GetSellerIdByAppUserIdAsync(int appUserId) {
            return base.Channel.GetSellerIdByAppUserIdAsync(appUserId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CozyComfortClient.SellerServiceReference.UpdateSellerProfileResponse CozyComfortClient.SellerServiceReference.SellerServiceSoap.UpdateSellerProfile(CozyComfortClient.SellerServiceReference.UpdateSellerProfileRequest request) {
            return base.Channel.UpdateSellerProfile(request);
        }
        
        public CozyComfortClient.SellerServiceReference.SellerOperationResult UpdateSellerProfile(CozyComfortClient.SellerServiceReference.Seller seller) {
            CozyComfortClient.SellerServiceReference.UpdateSellerProfileRequest inValue = new CozyComfortClient.SellerServiceReference.UpdateSellerProfileRequest();
            inValue.Body = new CozyComfortClient.SellerServiceReference.UpdateSellerProfileRequestBody();
            inValue.Body.seller = seller;
            CozyComfortClient.SellerServiceReference.UpdateSellerProfileResponse retVal = ((CozyComfortClient.SellerServiceReference.SellerServiceSoap)(this)).UpdateSellerProfile(inValue);
            return retVal.Body.UpdateSellerProfileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CozyComfortClient.SellerServiceReference.UpdateSellerProfileResponse> CozyComfortClient.SellerServiceReference.SellerServiceSoap.UpdateSellerProfileAsync(CozyComfortClient.SellerServiceReference.UpdateSellerProfileRequest request) {
            return base.Channel.UpdateSellerProfileAsync(request);
        }
        
        public System.Threading.Tasks.Task<CozyComfortClient.SellerServiceReference.UpdateSellerProfileResponse> UpdateSellerProfileAsync(CozyComfortClient.SellerServiceReference.Seller seller) {
            CozyComfortClient.SellerServiceReference.UpdateSellerProfileRequest inValue = new CozyComfortClient.SellerServiceReference.UpdateSellerProfileRequest();
            inValue.Body = new CozyComfortClient.SellerServiceReference.UpdateSellerProfileRequestBody();
            inValue.Body.seller = seller;
            return ((CozyComfortClient.SellerServiceReference.SellerServiceSoap)(this)).UpdateSellerProfileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CozyComfortClient.SellerServiceReference.GetSellerDetailsResponse CozyComfortClient.SellerServiceReference.SellerServiceSoap.GetSellerDetails(CozyComfortClient.SellerServiceReference.GetSellerDetailsRequest request) {
            return base.Channel.GetSellerDetails(request);
        }
        
        public CozyComfortClient.SellerServiceReference.Seller GetSellerDetails(int sellerId) {
            CozyComfortClient.SellerServiceReference.GetSellerDetailsRequest inValue = new CozyComfortClient.SellerServiceReference.GetSellerDetailsRequest();
            inValue.Body = new CozyComfortClient.SellerServiceReference.GetSellerDetailsRequestBody();
            inValue.Body.sellerId = sellerId;
            CozyComfortClient.SellerServiceReference.GetSellerDetailsResponse retVal = ((CozyComfortClient.SellerServiceReference.SellerServiceSoap)(this)).GetSellerDetails(inValue);
            return retVal.Body.GetSellerDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CozyComfortClient.SellerServiceReference.GetSellerDetailsResponse> CozyComfortClient.SellerServiceReference.SellerServiceSoap.GetSellerDetailsAsync(CozyComfortClient.SellerServiceReference.GetSellerDetailsRequest request) {
            return base.Channel.GetSellerDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<CozyComfortClient.SellerServiceReference.GetSellerDetailsResponse> GetSellerDetailsAsync(int sellerId) {
            CozyComfortClient.SellerServiceReference.GetSellerDetailsRequest inValue = new CozyComfortClient.SellerServiceReference.GetSellerDetailsRequest();
            inValue.Body = new CozyComfortClient.SellerServiceReference.GetSellerDetailsRequestBody();
            inValue.Body.sellerId = sellerId;
            return ((CozyComfortClient.SellerServiceReference.SellerServiceSoap)(this)).GetSellerDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CozyComfortClient.SellerServiceReference.GetAllSellersResponse CozyComfortClient.SellerServiceReference.SellerServiceSoap.GetAllSellers(CozyComfortClient.SellerServiceReference.GetAllSellersRequest request) {
            return base.Channel.GetAllSellers(request);
        }
        
        public CozyComfortClient.SellerServiceReference.Seller[] GetAllSellers() {
            CozyComfortClient.SellerServiceReference.GetAllSellersRequest inValue = new CozyComfortClient.SellerServiceReference.GetAllSellersRequest();
            inValue.Body = new CozyComfortClient.SellerServiceReference.GetAllSellersRequestBody();
            CozyComfortClient.SellerServiceReference.GetAllSellersResponse retVal = ((CozyComfortClient.SellerServiceReference.SellerServiceSoap)(this)).GetAllSellers(inValue);
            return retVal.Body.GetAllSellersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CozyComfortClient.SellerServiceReference.GetAllSellersResponse> CozyComfortClient.SellerServiceReference.SellerServiceSoap.GetAllSellersAsync(CozyComfortClient.SellerServiceReference.GetAllSellersRequest request) {
            return base.Channel.GetAllSellersAsync(request);
        }
        
        public System.Threading.Tasks.Task<CozyComfortClient.SellerServiceReference.GetAllSellersResponse> GetAllSellersAsync() {
            CozyComfortClient.SellerServiceReference.GetAllSellersRequest inValue = new CozyComfortClient.SellerServiceReference.GetAllSellersRequest();
            inValue.Body = new CozyComfortClient.SellerServiceReference.GetAllSellersRequestBody();
            return ((CozyComfortClient.SellerServiceReference.SellerServiceSoap)(this)).GetAllSellersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CozyComfortClient.SellerServiceReference.DeleteSellerResponse CozyComfortClient.SellerServiceReference.SellerServiceSoap.DeleteSeller(CozyComfortClient.SellerServiceReference.DeleteSellerRequest request) {
            return base.Channel.DeleteSeller(request);
        }
        
        public CozyComfortClient.SellerServiceReference.SellerOperationResult DeleteSeller(int sellerId) {
            CozyComfortClient.SellerServiceReference.DeleteSellerRequest inValue = new CozyComfortClient.SellerServiceReference.DeleteSellerRequest();
            inValue.Body = new CozyComfortClient.SellerServiceReference.DeleteSellerRequestBody();
            inValue.Body.sellerId = sellerId;
            CozyComfortClient.SellerServiceReference.DeleteSellerResponse retVal = ((CozyComfortClient.SellerServiceReference.SellerServiceSoap)(this)).DeleteSeller(inValue);
            return retVal.Body.DeleteSellerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CozyComfortClient.SellerServiceReference.DeleteSellerResponse> CozyComfortClient.SellerServiceReference.SellerServiceSoap.DeleteSellerAsync(CozyComfortClient.SellerServiceReference.DeleteSellerRequest request) {
            return base.Channel.DeleteSellerAsync(request);
        }
        
        public System.Threading.Tasks.Task<CozyComfortClient.SellerServiceReference.DeleteSellerResponse> DeleteSellerAsync(int sellerId) {
            CozyComfortClient.SellerServiceReference.DeleteSellerRequest inValue = new CozyComfortClient.SellerServiceReference.DeleteSellerRequest();
            inValue.Body = new CozyComfortClient.SellerServiceReference.DeleteSellerRequestBody();
            inValue.Body.sellerId = sellerId;
            return ((CozyComfortClient.SellerServiceReference.SellerServiceSoap)(this)).DeleteSellerAsync(inValue);
        }
    }
}
