//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CozyComfortClient.SInventoryServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SInventory", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SInventory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int SInventoryIDField;
        
        private int SellerIDField;
        
        private int SBlanketIDField;
        
        private int SQuantityField;
        
        private System.DateTime SLastUpdatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaterialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SInventoryID {
            get {
                return this.SInventoryIDField;
            }
            set {
                if ((this.SInventoryIDField.Equals(value) != true)) {
                    this.SInventoryIDField = value;
                    this.RaisePropertyChanged("SInventoryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SellerID {
            get {
                return this.SellerIDField;
            }
            set {
                if ((this.SellerIDField.Equals(value) != true)) {
                    this.SellerIDField = value;
                    this.RaisePropertyChanged("SellerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int SBlanketID {
            get {
                return this.SBlanketIDField;
            }
            set {
                if ((this.SBlanketIDField.Equals(value) != true)) {
                    this.SBlanketIDField = value;
                    this.RaisePropertyChanged("SBlanketID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int SQuantity {
            get {
                return this.SQuantityField;
            }
            set {
                if ((this.SQuantityField.Equals(value) != true)) {
                    this.SQuantityField = value;
                    this.RaisePropertyChanged("SQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime SLastUpdated {
            get {
                return this.SLastUpdatedField;
            }
            set {
                if ((this.SLastUpdatedField.Equals(value) != true)) {
                    this.SLastUpdatedField = value;
                    this.RaisePropertyChanged("SLastUpdated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Material {
            get {
                return this.MaterialField;
            }
            set {
                if ((object.ReferenceEquals(this.MaterialField, value) != true)) {
                    this.MaterialField = value;
                    this.RaisePropertyChanged("Material");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InventoryOperationResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class InventoryOperationResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        private int InventoryIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int InventoryId {
            get {
                return this.InventoryIdField;
            }
            set {
                if ((this.InventoryIdField.Equals(value) != true)) {
                    this.InventoryIdField = value;
                    this.RaisePropertyChanged("InventoryId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SInventoryServiceReference.SInventoryServiceSoap")]
    public interface SInventoryServiceSoap {
        
        // CODEGEN: Generating message contract since element name inv from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddSInventory", ReplyAction="*")]
        CozyComfortClient.SInventoryServiceReference.AddSInventoryResponse AddSInventory(CozyComfortClient.SInventoryServiceReference.AddSInventoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddSInventory", ReplyAction="*")]
        System.Threading.Tasks.Task<CozyComfortClient.SInventoryServiceReference.AddSInventoryResponse> AddSInventoryAsync(CozyComfortClient.SInventoryServiceReference.AddSInventoryRequest request);
        
        // CODEGEN: Generating message contract since element name inv from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateSInventory", ReplyAction="*")]
        CozyComfortClient.SInventoryServiceReference.UpdateSInventoryResponse UpdateSInventory(CozyComfortClient.SInventoryServiceReference.UpdateSInventoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateSInventory", ReplyAction="*")]
        System.Threading.Tasks.Task<CozyComfortClient.SInventoryServiceReference.UpdateSInventoryResponse> UpdateSInventoryAsync(CozyComfortClient.SInventoryServiceReference.UpdateSInventoryRequest request);
        
        // CODEGEN: Generating message contract since element name DeleteSInventoryResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteSInventory", ReplyAction="*")]
        CozyComfortClient.SInventoryServiceReference.DeleteSInventoryResponse DeleteSInventory(CozyComfortClient.SInventoryServiceReference.DeleteSInventoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteSInventory", ReplyAction="*")]
        System.Threading.Tasks.Task<CozyComfortClient.SInventoryServiceReference.DeleteSInventoryResponse> DeleteSInventoryAsync(CozyComfortClient.SInventoryServiceReference.DeleteSInventoryRequest request);
        
        // CODEGEN: Generating message contract since element name GetSInventoriesBySellerResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSInventoriesBySeller", ReplyAction="*")]
        CozyComfortClient.SInventoryServiceReference.GetSInventoriesBySellerResponse GetSInventoriesBySeller(CozyComfortClient.SInventoryServiceReference.GetSInventoriesBySellerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSInventoriesBySeller", ReplyAction="*")]
        System.Threading.Tasks.Task<CozyComfortClient.SInventoryServiceReference.GetSInventoriesBySellerResponse> GetSInventoriesBySellerAsync(CozyComfortClient.SInventoryServiceReference.GetSInventoriesBySellerRequest request);
        
        // CODEGEN: Generating message contract since element name GetSInventoryByIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSInventoryById", ReplyAction="*")]
        CozyComfortClient.SInventoryServiceReference.GetSInventoryByIdResponse GetSInventoryById(CozyComfortClient.SInventoryServiceReference.GetSInventoryByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSInventoryById", ReplyAction="*")]
        System.Threading.Tasks.Task<CozyComfortClient.SInventoryServiceReference.GetSInventoryByIdResponse> GetSInventoryByIdAsync(CozyComfortClient.SInventoryServiceReference.GetSInventoryByIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddSInventoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddSInventory", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.SInventoryServiceReference.AddSInventoryRequestBody Body;
        
        public AddSInventoryRequest() {
        }
        
        public AddSInventoryRequest(CozyComfortClient.SInventoryServiceReference.AddSInventoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddSInventoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CozyComfortClient.SInventoryServiceReference.SInventory inv;
        
        public AddSInventoryRequestBody() {
        }
        
        public AddSInventoryRequestBody(CozyComfortClient.SInventoryServiceReference.SInventory inv) {
            this.inv = inv;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddSInventoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddSInventoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.SInventoryServiceReference.AddSInventoryResponseBody Body;
        
        public AddSInventoryResponse() {
        }
        
        public AddSInventoryResponse(CozyComfortClient.SInventoryServiceReference.AddSInventoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddSInventoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CozyComfortClient.SInventoryServiceReference.InventoryOperationResult AddSInventoryResult;
        
        public AddSInventoryResponseBody() {
        }
        
        public AddSInventoryResponseBody(CozyComfortClient.SInventoryServiceReference.InventoryOperationResult AddSInventoryResult) {
            this.AddSInventoryResult = AddSInventoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateSInventoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateSInventory", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.SInventoryServiceReference.UpdateSInventoryRequestBody Body;
        
        public UpdateSInventoryRequest() {
        }
        
        public UpdateSInventoryRequest(CozyComfortClient.SInventoryServiceReference.UpdateSInventoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateSInventoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CozyComfortClient.SInventoryServiceReference.SInventory inv;
        
        public UpdateSInventoryRequestBody() {
        }
        
        public UpdateSInventoryRequestBody(CozyComfortClient.SInventoryServiceReference.SInventory inv) {
            this.inv = inv;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateSInventoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateSInventoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.SInventoryServiceReference.UpdateSInventoryResponseBody Body;
        
        public UpdateSInventoryResponse() {
        }
        
        public UpdateSInventoryResponse(CozyComfortClient.SInventoryServiceReference.UpdateSInventoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateSInventoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CozyComfortClient.SInventoryServiceReference.InventoryOperationResult UpdateSInventoryResult;
        
        public UpdateSInventoryResponseBody() {
        }
        
        public UpdateSInventoryResponseBody(CozyComfortClient.SInventoryServiceReference.InventoryOperationResult UpdateSInventoryResult) {
            this.UpdateSInventoryResult = UpdateSInventoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteSInventoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteSInventory", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.SInventoryServiceReference.DeleteSInventoryRequestBody Body;
        
        public DeleteSInventoryRequest() {
        }
        
        public DeleteSInventoryRequest(CozyComfortClient.SInventoryServiceReference.DeleteSInventoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteSInventoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int sInventoryId;
        
        public DeleteSInventoryRequestBody() {
        }
        
        public DeleteSInventoryRequestBody(int sInventoryId) {
            this.sInventoryId = sInventoryId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteSInventoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteSInventoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.SInventoryServiceReference.DeleteSInventoryResponseBody Body;
        
        public DeleteSInventoryResponse() {
        }
        
        public DeleteSInventoryResponse(CozyComfortClient.SInventoryServiceReference.DeleteSInventoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteSInventoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CozyComfortClient.SInventoryServiceReference.InventoryOperationResult DeleteSInventoryResult;
        
        public DeleteSInventoryResponseBody() {
        }
        
        public DeleteSInventoryResponseBody(CozyComfortClient.SInventoryServiceReference.InventoryOperationResult DeleteSInventoryResult) {
            this.DeleteSInventoryResult = DeleteSInventoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSInventoriesBySellerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSInventoriesBySeller", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.SInventoryServiceReference.GetSInventoriesBySellerRequestBody Body;
        
        public GetSInventoriesBySellerRequest() {
        }
        
        public GetSInventoriesBySellerRequest(CozyComfortClient.SInventoryServiceReference.GetSInventoriesBySellerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSInventoriesBySellerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int sellerId;
        
        public GetSInventoriesBySellerRequestBody() {
        }
        
        public GetSInventoriesBySellerRequestBody(int sellerId) {
            this.sellerId = sellerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSInventoriesBySellerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSInventoriesBySellerResponse", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.SInventoryServiceReference.GetSInventoriesBySellerResponseBody Body;
        
        public GetSInventoriesBySellerResponse() {
        }
        
        public GetSInventoriesBySellerResponse(CozyComfortClient.SInventoryServiceReference.GetSInventoriesBySellerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSInventoriesBySellerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CozyComfortClient.SInventoryServiceReference.SInventory[] GetSInventoriesBySellerResult;
        
        public GetSInventoriesBySellerResponseBody() {
        }
        
        public GetSInventoriesBySellerResponseBody(CozyComfortClient.SInventoryServiceReference.SInventory[] GetSInventoriesBySellerResult) {
            this.GetSInventoriesBySellerResult = GetSInventoriesBySellerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSInventoryByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSInventoryById", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.SInventoryServiceReference.GetSInventoryByIdRequestBody Body;
        
        public GetSInventoryByIdRequest() {
        }
        
        public GetSInventoryByIdRequest(CozyComfortClient.SInventoryServiceReference.GetSInventoryByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSInventoryByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int inventoryId;
        
        public GetSInventoryByIdRequestBody() {
        }
        
        public GetSInventoryByIdRequestBody(int inventoryId) {
            this.inventoryId = inventoryId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSInventoryByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSInventoryByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.SInventoryServiceReference.GetSInventoryByIdResponseBody Body;
        
        public GetSInventoryByIdResponse() {
        }
        
        public GetSInventoryByIdResponse(CozyComfortClient.SInventoryServiceReference.GetSInventoryByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSInventoryByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CozyComfortClient.SInventoryServiceReference.SInventory GetSInventoryByIdResult;
        
        public GetSInventoryByIdResponseBody() {
        }
        
        public GetSInventoryByIdResponseBody(CozyComfortClient.SInventoryServiceReference.SInventory GetSInventoryByIdResult) {
            this.GetSInventoryByIdResult = GetSInventoryByIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SInventoryServiceSoapChannel : CozyComfortClient.SInventoryServiceReference.SInventoryServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SInventoryServiceSoapClient : System.ServiceModel.ClientBase<CozyComfortClient.SInventoryServiceReference.SInventoryServiceSoap>, CozyComfortClient.SInventoryServiceReference.SInventoryServiceSoap {
        
        public SInventoryServiceSoapClient() {
        }
        
        public SInventoryServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SInventoryServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SInventoryServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SInventoryServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CozyComfortClient.SInventoryServiceReference.AddSInventoryResponse CozyComfortClient.SInventoryServiceReference.SInventoryServiceSoap.AddSInventory(CozyComfortClient.SInventoryServiceReference.AddSInventoryRequest request) {
            return base.Channel.AddSInventory(request);
        }
        
        public CozyComfortClient.SInventoryServiceReference.InventoryOperationResult AddSInventory(CozyComfortClient.SInventoryServiceReference.SInventory inv) {
            CozyComfortClient.SInventoryServiceReference.AddSInventoryRequest inValue = new CozyComfortClient.SInventoryServiceReference.AddSInventoryRequest();
            inValue.Body = new CozyComfortClient.SInventoryServiceReference.AddSInventoryRequestBody();
            inValue.Body.inv = inv;
            CozyComfortClient.SInventoryServiceReference.AddSInventoryResponse retVal = ((CozyComfortClient.SInventoryServiceReference.SInventoryServiceSoap)(this)).AddSInventory(inValue);
            return retVal.Body.AddSInventoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CozyComfortClient.SInventoryServiceReference.AddSInventoryResponse> CozyComfortClient.SInventoryServiceReference.SInventoryServiceSoap.AddSInventoryAsync(CozyComfortClient.SInventoryServiceReference.AddSInventoryRequest request) {
            return base.Channel.AddSInventoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<CozyComfortClient.SInventoryServiceReference.AddSInventoryResponse> AddSInventoryAsync(CozyComfortClient.SInventoryServiceReference.SInventory inv) {
            CozyComfortClient.SInventoryServiceReference.AddSInventoryRequest inValue = new CozyComfortClient.SInventoryServiceReference.AddSInventoryRequest();
            inValue.Body = new CozyComfortClient.SInventoryServiceReference.AddSInventoryRequestBody();
            inValue.Body.inv = inv;
            return ((CozyComfortClient.SInventoryServiceReference.SInventoryServiceSoap)(this)).AddSInventoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CozyComfortClient.SInventoryServiceReference.UpdateSInventoryResponse CozyComfortClient.SInventoryServiceReference.SInventoryServiceSoap.UpdateSInventory(CozyComfortClient.SInventoryServiceReference.UpdateSInventoryRequest request) {
            return base.Channel.UpdateSInventory(request);
        }
        
        public CozyComfortClient.SInventoryServiceReference.InventoryOperationResult UpdateSInventory(CozyComfortClient.SInventoryServiceReference.SInventory inv) {
            CozyComfortClient.SInventoryServiceReference.UpdateSInventoryRequest inValue = new CozyComfortClient.SInventoryServiceReference.UpdateSInventoryRequest();
            inValue.Body = new CozyComfortClient.SInventoryServiceReference.UpdateSInventoryRequestBody();
            inValue.Body.inv = inv;
            CozyComfortClient.SInventoryServiceReference.UpdateSInventoryResponse retVal = ((CozyComfortClient.SInventoryServiceReference.SInventoryServiceSoap)(this)).UpdateSInventory(inValue);
            return retVal.Body.UpdateSInventoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CozyComfortClient.SInventoryServiceReference.UpdateSInventoryResponse> CozyComfortClient.SInventoryServiceReference.SInventoryServiceSoap.UpdateSInventoryAsync(CozyComfortClient.SInventoryServiceReference.UpdateSInventoryRequest request) {
            return base.Channel.UpdateSInventoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<CozyComfortClient.SInventoryServiceReference.UpdateSInventoryResponse> UpdateSInventoryAsync(CozyComfortClient.SInventoryServiceReference.SInventory inv) {
            CozyComfortClient.SInventoryServiceReference.UpdateSInventoryRequest inValue = new CozyComfortClient.SInventoryServiceReference.UpdateSInventoryRequest();
            inValue.Body = new CozyComfortClient.SInventoryServiceReference.UpdateSInventoryRequestBody();
            inValue.Body.inv = inv;
            return ((CozyComfortClient.SInventoryServiceReference.SInventoryServiceSoap)(this)).UpdateSInventoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CozyComfortClient.SInventoryServiceReference.DeleteSInventoryResponse CozyComfortClient.SInventoryServiceReference.SInventoryServiceSoap.DeleteSInventory(CozyComfortClient.SInventoryServiceReference.DeleteSInventoryRequest request) {
            return base.Channel.DeleteSInventory(request);
        }
        
        public CozyComfortClient.SInventoryServiceReference.InventoryOperationResult DeleteSInventory(int sInventoryId) {
            CozyComfortClient.SInventoryServiceReference.DeleteSInventoryRequest inValue = new CozyComfortClient.SInventoryServiceReference.DeleteSInventoryRequest();
            inValue.Body = new CozyComfortClient.SInventoryServiceReference.DeleteSInventoryRequestBody();
            inValue.Body.sInventoryId = sInventoryId;
            CozyComfortClient.SInventoryServiceReference.DeleteSInventoryResponse retVal = ((CozyComfortClient.SInventoryServiceReference.SInventoryServiceSoap)(this)).DeleteSInventory(inValue);
            return retVal.Body.DeleteSInventoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CozyComfortClient.SInventoryServiceReference.DeleteSInventoryResponse> CozyComfortClient.SInventoryServiceReference.SInventoryServiceSoap.DeleteSInventoryAsync(CozyComfortClient.SInventoryServiceReference.DeleteSInventoryRequest request) {
            return base.Channel.DeleteSInventoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<CozyComfortClient.SInventoryServiceReference.DeleteSInventoryResponse> DeleteSInventoryAsync(int sInventoryId) {
            CozyComfortClient.SInventoryServiceReference.DeleteSInventoryRequest inValue = new CozyComfortClient.SInventoryServiceReference.DeleteSInventoryRequest();
            inValue.Body = new CozyComfortClient.SInventoryServiceReference.DeleteSInventoryRequestBody();
            inValue.Body.sInventoryId = sInventoryId;
            return ((CozyComfortClient.SInventoryServiceReference.SInventoryServiceSoap)(this)).DeleteSInventoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CozyComfortClient.SInventoryServiceReference.GetSInventoriesBySellerResponse CozyComfortClient.SInventoryServiceReference.SInventoryServiceSoap.GetSInventoriesBySeller(CozyComfortClient.SInventoryServiceReference.GetSInventoriesBySellerRequest request) {
            return base.Channel.GetSInventoriesBySeller(request);
        }
        
        public CozyComfortClient.SInventoryServiceReference.SInventory[] GetSInventoriesBySeller(int sellerId) {
            CozyComfortClient.SInventoryServiceReference.GetSInventoriesBySellerRequest inValue = new CozyComfortClient.SInventoryServiceReference.GetSInventoriesBySellerRequest();
            inValue.Body = new CozyComfortClient.SInventoryServiceReference.GetSInventoriesBySellerRequestBody();
            inValue.Body.sellerId = sellerId;
            CozyComfortClient.SInventoryServiceReference.GetSInventoriesBySellerResponse retVal = ((CozyComfortClient.SInventoryServiceReference.SInventoryServiceSoap)(this)).GetSInventoriesBySeller(inValue);
            return retVal.Body.GetSInventoriesBySellerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CozyComfortClient.SInventoryServiceReference.GetSInventoriesBySellerResponse> CozyComfortClient.SInventoryServiceReference.SInventoryServiceSoap.GetSInventoriesBySellerAsync(CozyComfortClient.SInventoryServiceReference.GetSInventoriesBySellerRequest request) {
            return base.Channel.GetSInventoriesBySellerAsync(request);
        }
        
        public System.Threading.Tasks.Task<CozyComfortClient.SInventoryServiceReference.GetSInventoriesBySellerResponse> GetSInventoriesBySellerAsync(int sellerId) {
            CozyComfortClient.SInventoryServiceReference.GetSInventoriesBySellerRequest inValue = new CozyComfortClient.SInventoryServiceReference.GetSInventoriesBySellerRequest();
            inValue.Body = new CozyComfortClient.SInventoryServiceReference.GetSInventoriesBySellerRequestBody();
            inValue.Body.sellerId = sellerId;
            return ((CozyComfortClient.SInventoryServiceReference.SInventoryServiceSoap)(this)).GetSInventoriesBySellerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CozyComfortClient.SInventoryServiceReference.GetSInventoryByIdResponse CozyComfortClient.SInventoryServiceReference.SInventoryServiceSoap.GetSInventoryById(CozyComfortClient.SInventoryServiceReference.GetSInventoryByIdRequest request) {
            return base.Channel.GetSInventoryById(request);
        }
        
        public CozyComfortClient.SInventoryServiceReference.SInventory GetSInventoryById(int inventoryId) {
            CozyComfortClient.SInventoryServiceReference.GetSInventoryByIdRequest inValue = new CozyComfortClient.SInventoryServiceReference.GetSInventoryByIdRequest();
            inValue.Body = new CozyComfortClient.SInventoryServiceReference.GetSInventoryByIdRequestBody();
            inValue.Body.inventoryId = inventoryId;
            CozyComfortClient.SInventoryServiceReference.GetSInventoryByIdResponse retVal = ((CozyComfortClient.SInventoryServiceReference.SInventoryServiceSoap)(this)).GetSInventoryById(inValue);
            return retVal.Body.GetSInventoryByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CozyComfortClient.SInventoryServiceReference.GetSInventoryByIdResponse> CozyComfortClient.SInventoryServiceReference.SInventoryServiceSoap.GetSInventoryByIdAsync(CozyComfortClient.SInventoryServiceReference.GetSInventoryByIdRequest request) {
            return base.Channel.GetSInventoryByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<CozyComfortClient.SInventoryServiceReference.GetSInventoryByIdResponse> GetSInventoryByIdAsync(int inventoryId) {
            CozyComfortClient.SInventoryServiceReference.GetSInventoryByIdRequest inValue = new CozyComfortClient.SInventoryServiceReference.GetSInventoryByIdRequest();
            inValue.Body = new CozyComfortClient.SInventoryServiceReference.GetSInventoryByIdRequestBody();
            inValue.Body.inventoryId = inventoryId;
            return ((CozyComfortClient.SInventoryServiceReference.SInventoryServiceSoap)(this)).GetSInventoryByIdAsync(inValue);
        }
    }
}
