//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CozyComfortClient.DistributorServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DistributorDetails", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DistributorDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int DistributorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BusinessNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WarehouseLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LicenseNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int DistributorId {
            get {
                return this.DistributorIdField;
            }
            set {
                if ((this.DistributorIdField.Equals(value) != true)) {
                    this.DistributorIdField = value;
                    this.RaisePropertyChanged("DistributorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BusinessName {
            get {
                return this.BusinessNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BusinessNameField, value) != true)) {
                    this.BusinessNameField = value;
                    this.RaisePropertyChanged("BusinessName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ContactNumber {
            get {
                return this.ContactNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactNumberField, value) != true)) {
                    this.ContactNumberField = value;
                    this.RaisePropertyChanged("ContactNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string WarehouseLocation {
            get {
                return this.WarehouseLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.WarehouseLocationField, value) != true)) {
                    this.WarehouseLocationField = value;
                    this.RaisePropertyChanged("WarehouseLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string LicenseNumber {
            get {
                return this.LicenseNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.LicenseNumberField, value) != true)) {
                    this.LicenseNumberField = value;
                    this.RaisePropertyChanged("LicenseNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DistributorServiceReference.DistributorServiceSoap")]
    public interface DistributorServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDistributorIdByAppUserId", ReplyAction="*")]
        int GetDistributorIdByAppUserId(int appUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDistributorIdByAppUserId", ReplyAction="*")]
        System.Threading.Tasks.Task<int> GetDistributorIdByAppUserIdAsync(int appUserId);
        
        // CODEGEN: Generating message contract since element name GetDistributorDetailsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDistributorDetails", ReplyAction="*")]
        CozyComfortClient.DistributorServiceReference.GetDistributorDetailsResponse GetDistributorDetails(CozyComfortClient.DistributorServiceReference.GetDistributorDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDistributorDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<CozyComfortClient.DistributorServiceReference.GetDistributorDetailsResponse> GetDistributorDetailsAsync(CozyComfortClient.DistributorServiceReference.GetDistributorDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllDistributorsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllDistributors", ReplyAction="*")]
        CozyComfortClient.DistributorServiceReference.GetAllDistributorsResponse GetAllDistributors(CozyComfortClient.DistributorServiceReference.GetAllDistributorsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllDistributors", ReplyAction="*")]
        System.Threading.Tasks.Task<CozyComfortClient.DistributorServiceReference.GetAllDistributorsResponse> GetAllDistributorsAsync(CozyComfortClient.DistributorServiceReference.GetAllDistributorsRequest request);
        
        // CODEGEN: Generating message contract since element name GetDistributorCompanyNameResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDistributorCompanyName", ReplyAction="*")]
        CozyComfortClient.DistributorServiceReference.GetDistributorCompanyNameResponse GetDistributorCompanyName(CozyComfortClient.DistributorServiceReference.GetDistributorCompanyNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDistributorCompanyName", ReplyAction="*")]
        System.Threading.Tasks.Task<CozyComfortClient.DistributorServiceReference.GetDistributorCompanyNameResponse> GetDistributorCompanyNameAsync(CozyComfortClient.DistributorServiceReference.GetDistributorCompanyNameRequest request);
        
        // CODEGEN: Generating message contract since element name businessName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateDistributorProfile", ReplyAction="*")]
        CozyComfortClient.DistributorServiceReference.UpdateDistributorProfileResponse UpdateDistributorProfile(CozyComfortClient.DistributorServiceReference.UpdateDistributorProfileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateDistributorProfile", ReplyAction="*")]
        System.Threading.Tasks.Task<CozyComfortClient.DistributorServiceReference.UpdateDistributorProfileResponse> UpdateDistributorProfileAsync(CozyComfortClient.DistributorServiceReference.UpdateDistributorProfileRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDistributorDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDistributorDetails", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.DistributorServiceReference.GetDistributorDetailsRequestBody Body;
        
        public GetDistributorDetailsRequest() {
        }
        
        public GetDistributorDetailsRequest(CozyComfortClient.DistributorServiceReference.GetDistributorDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDistributorDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int distributorId;
        
        public GetDistributorDetailsRequestBody() {
        }
        
        public GetDistributorDetailsRequestBody(int distributorId) {
            this.distributorId = distributorId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDistributorDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDistributorDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.DistributorServiceReference.GetDistributorDetailsResponseBody Body;
        
        public GetDistributorDetailsResponse() {
        }
        
        public GetDistributorDetailsResponse(CozyComfortClient.DistributorServiceReference.GetDistributorDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDistributorDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CozyComfortClient.DistributorServiceReference.DistributorDetails GetDistributorDetailsResult;
        
        public GetDistributorDetailsResponseBody() {
        }
        
        public GetDistributorDetailsResponseBody(CozyComfortClient.DistributorServiceReference.DistributorDetails GetDistributorDetailsResult) {
            this.GetDistributorDetailsResult = GetDistributorDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllDistributorsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllDistributors", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.DistributorServiceReference.GetAllDistributorsRequestBody Body;
        
        public GetAllDistributorsRequest() {
        }
        
        public GetAllDistributorsRequest(CozyComfortClient.DistributorServiceReference.GetAllDistributorsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllDistributorsRequestBody {
        
        public GetAllDistributorsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllDistributorsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllDistributorsResponse", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.DistributorServiceReference.GetAllDistributorsResponseBody Body;
        
        public GetAllDistributorsResponse() {
        }
        
        public GetAllDistributorsResponse(CozyComfortClient.DistributorServiceReference.GetAllDistributorsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllDistributorsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CozyComfortClient.DistributorServiceReference.DistributorDetails[] GetAllDistributorsResult;
        
        public GetAllDistributorsResponseBody() {
        }
        
        public GetAllDistributorsResponseBody(CozyComfortClient.DistributorServiceReference.DistributorDetails[] GetAllDistributorsResult) {
            this.GetAllDistributorsResult = GetAllDistributorsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDistributorCompanyNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDistributorCompanyName", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.DistributorServiceReference.GetDistributorCompanyNameRequestBody Body;
        
        public GetDistributorCompanyNameRequest() {
        }
        
        public GetDistributorCompanyNameRequest(CozyComfortClient.DistributorServiceReference.GetDistributorCompanyNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDistributorCompanyNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int distributorId;
        
        public GetDistributorCompanyNameRequestBody() {
        }
        
        public GetDistributorCompanyNameRequestBody(int distributorId) {
            this.distributorId = distributorId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDistributorCompanyNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDistributorCompanyNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.DistributorServiceReference.GetDistributorCompanyNameResponseBody Body;
        
        public GetDistributorCompanyNameResponse() {
        }
        
        public GetDistributorCompanyNameResponse(CozyComfortClient.DistributorServiceReference.GetDistributorCompanyNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDistributorCompanyNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDistributorCompanyNameResult;
        
        public GetDistributorCompanyNameResponseBody() {
        }
        
        public GetDistributorCompanyNameResponseBody(string GetDistributorCompanyNameResult) {
            this.GetDistributorCompanyNameResult = GetDistributorCompanyNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateDistributorProfileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateDistributorProfile", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.DistributorServiceReference.UpdateDistributorProfileRequestBody Body;
        
        public UpdateDistributorProfileRequest() {
        }
        
        public UpdateDistributorProfileRequest(CozyComfortClient.DistributorServiceReference.UpdateDistributorProfileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateDistributorProfileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int distributorId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string businessName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string contactNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string warehouseLocation;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string licenseNumber;
        
        public UpdateDistributorProfileRequestBody() {
        }
        
        public UpdateDistributorProfileRequestBody(int distributorId, string businessName, string contactNumber, string warehouseLocation, string licenseNumber) {
            this.distributorId = distributorId;
            this.businessName = businessName;
            this.contactNumber = contactNumber;
            this.warehouseLocation = warehouseLocation;
            this.licenseNumber = licenseNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateDistributorProfileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateDistributorProfileResponse", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.DistributorServiceReference.UpdateDistributorProfileResponseBody Body;
        
        public UpdateDistributorProfileResponse() {
        }
        
        public UpdateDistributorProfileResponse(CozyComfortClient.DistributorServiceReference.UpdateDistributorProfileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateDistributorProfileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateDistributorProfileResult;
        
        public UpdateDistributorProfileResponseBody() {
        }
        
        public UpdateDistributorProfileResponseBody(string UpdateDistributorProfileResult) {
            this.UpdateDistributorProfileResult = UpdateDistributorProfileResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DistributorServiceSoapChannel : CozyComfortClient.DistributorServiceReference.DistributorServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DistributorServiceSoapClient : System.ServiceModel.ClientBase<CozyComfortClient.DistributorServiceReference.DistributorServiceSoap>, CozyComfortClient.DistributorServiceReference.DistributorServiceSoap {
        
        public DistributorServiceSoapClient() {
        }
        
        public DistributorServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DistributorServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DistributorServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DistributorServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetDistributorIdByAppUserId(int appUserId) {
            return base.Channel.GetDistributorIdByAppUserId(appUserId);
        }
        
        public System.Threading.Tasks.Task<int> GetDistributorIdByAppUserIdAsync(int appUserId) {
            return base.Channel.GetDistributorIdByAppUserIdAsync(appUserId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CozyComfortClient.DistributorServiceReference.GetDistributorDetailsResponse CozyComfortClient.DistributorServiceReference.DistributorServiceSoap.GetDistributorDetails(CozyComfortClient.DistributorServiceReference.GetDistributorDetailsRequest request) {
            return base.Channel.GetDistributorDetails(request);
        }
        
        public CozyComfortClient.DistributorServiceReference.DistributorDetails GetDistributorDetails(int distributorId) {
            CozyComfortClient.DistributorServiceReference.GetDistributorDetailsRequest inValue = new CozyComfortClient.DistributorServiceReference.GetDistributorDetailsRequest();
            inValue.Body = new CozyComfortClient.DistributorServiceReference.GetDistributorDetailsRequestBody();
            inValue.Body.distributorId = distributorId;
            CozyComfortClient.DistributorServiceReference.GetDistributorDetailsResponse retVal = ((CozyComfortClient.DistributorServiceReference.DistributorServiceSoap)(this)).GetDistributorDetails(inValue);
            return retVal.Body.GetDistributorDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CozyComfortClient.DistributorServiceReference.GetDistributorDetailsResponse> CozyComfortClient.DistributorServiceReference.DistributorServiceSoap.GetDistributorDetailsAsync(CozyComfortClient.DistributorServiceReference.GetDistributorDetailsRequest request) {
            return base.Channel.GetDistributorDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<CozyComfortClient.DistributorServiceReference.GetDistributorDetailsResponse> GetDistributorDetailsAsync(int distributorId) {
            CozyComfortClient.DistributorServiceReference.GetDistributorDetailsRequest inValue = new CozyComfortClient.DistributorServiceReference.GetDistributorDetailsRequest();
            inValue.Body = new CozyComfortClient.DistributorServiceReference.GetDistributorDetailsRequestBody();
            inValue.Body.distributorId = distributorId;
            return ((CozyComfortClient.DistributorServiceReference.DistributorServiceSoap)(this)).GetDistributorDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CozyComfortClient.DistributorServiceReference.GetAllDistributorsResponse CozyComfortClient.DistributorServiceReference.DistributorServiceSoap.GetAllDistributors(CozyComfortClient.DistributorServiceReference.GetAllDistributorsRequest request) {
            return base.Channel.GetAllDistributors(request);
        }
        
        public CozyComfortClient.DistributorServiceReference.DistributorDetails[] GetAllDistributors() {
            CozyComfortClient.DistributorServiceReference.GetAllDistributorsRequest inValue = new CozyComfortClient.DistributorServiceReference.GetAllDistributorsRequest();
            inValue.Body = new CozyComfortClient.DistributorServiceReference.GetAllDistributorsRequestBody();
            CozyComfortClient.DistributorServiceReference.GetAllDistributorsResponse retVal = ((CozyComfortClient.DistributorServiceReference.DistributorServiceSoap)(this)).GetAllDistributors(inValue);
            return retVal.Body.GetAllDistributorsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CozyComfortClient.DistributorServiceReference.GetAllDistributorsResponse> CozyComfortClient.DistributorServiceReference.DistributorServiceSoap.GetAllDistributorsAsync(CozyComfortClient.DistributorServiceReference.GetAllDistributorsRequest request) {
            return base.Channel.GetAllDistributorsAsync(request);
        }
        
        public System.Threading.Tasks.Task<CozyComfortClient.DistributorServiceReference.GetAllDistributorsResponse> GetAllDistributorsAsync() {
            CozyComfortClient.DistributorServiceReference.GetAllDistributorsRequest inValue = new CozyComfortClient.DistributorServiceReference.GetAllDistributorsRequest();
            inValue.Body = new CozyComfortClient.DistributorServiceReference.GetAllDistributorsRequestBody();
            return ((CozyComfortClient.DistributorServiceReference.DistributorServiceSoap)(this)).GetAllDistributorsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CozyComfortClient.DistributorServiceReference.GetDistributorCompanyNameResponse CozyComfortClient.DistributorServiceReference.DistributorServiceSoap.GetDistributorCompanyName(CozyComfortClient.DistributorServiceReference.GetDistributorCompanyNameRequest request) {
            return base.Channel.GetDistributorCompanyName(request);
        }
        
        public string GetDistributorCompanyName(int distributorId) {
            CozyComfortClient.DistributorServiceReference.GetDistributorCompanyNameRequest inValue = new CozyComfortClient.DistributorServiceReference.GetDistributorCompanyNameRequest();
            inValue.Body = new CozyComfortClient.DistributorServiceReference.GetDistributorCompanyNameRequestBody();
            inValue.Body.distributorId = distributorId;
            CozyComfortClient.DistributorServiceReference.GetDistributorCompanyNameResponse retVal = ((CozyComfortClient.DistributorServiceReference.DistributorServiceSoap)(this)).GetDistributorCompanyName(inValue);
            return retVal.Body.GetDistributorCompanyNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CozyComfortClient.DistributorServiceReference.GetDistributorCompanyNameResponse> CozyComfortClient.DistributorServiceReference.DistributorServiceSoap.GetDistributorCompanyNameAsync(CozyComfortClient.DistributorServiceReference.GetDistributorCompanyNameRequest request) {
            return base.Channel.GetDistributorCompanyNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<CozyComfortClient.DistributorServiceReference.GetDistributorCompanyNameResponse> GetDistributorCompanyNameAsync(int distributorId) {
            CozyComfortClient.DistributorServiceReference.GetDistributorCompanyNameRequest inValue = new CozyComfortClient.DistributorServiceReference.GetDistributorCompanyNameRequest();
            inValue.Body = new CozyComfortClient.DistributorServiceReference.GetDistributorCompanyNameRequestBody();
            inValue.Body.distributorId = distributorId;
            return ((CozyComfortClient.DistributorServiceReference.DistributorServiceSoap)(this)).GetDistributorCompanyNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CozyComfortClient.DistributorServiceReference.UpdateDistributorProfileResponse CozyComfortClient.DistributorServiceReference.DistributorServiceSoap.UpdateDistributorProfile(CozyComfortClient.DistributorServiceReference.UpdateDistributorProfileRequest request) {
            return base.Channel.UpdateDistributorProfile(request);
        }
        
        public string UpdateDistributorProfile(int distributorId, string businessName, string contactNumber, string warehouseLocation, string licenseNumber) {
            CozyComfortClient.DistributorServiceReference.UpdateDistributorProfileRequest inValue = new CozyComfortClient.DistributorServiceReference.UpdateDistributorProfileRequest();
            inValue.Body = new CozyComfortClient.DistributorServiceReference.UpdateDistributorProfileRequestBody();
            inValue.Body.distributorId = distributorId;
            inValue.Body.businessName = businessName;
            inValue.Body.contactNumber = contactNumber;
            inValue.Body.warehouseLocation = warehouseLocation;
            inValue.Body.licenseNumber = licenseNumber;
            CozyComfortClient.DistributorServiceReference.UpdateDistributorProfileResponse retVal = ((CozyComfortClient.DistributorServiceReference.DistributorServiceSoap)(this)).UpdateDistributorProfile(inValue);
            return retVal.Body.UpdateDistributorProfileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CozyComfortClient.DistributorServiceReference.UpdateDistributorProfileResponse> CozyComfortClient.DistributorServiceReference.DistributorServiceSoap.UpdateDistributorProfileAsync(CozyComfortClient.DistributorServiceReference.UpdateDistributorProfileRequest request) {
            return base.Channel.UpdateDistributorProfileAsync(request);
        }
        
        public System.Threading.Tasks.Task<CozyComfortClient.DistributorServiceReference.UpdateDistributorProfileResponse> UpdateDistributorProfileAsync(int distributorId, string businessName, string contactNumber, string warehouseLocation, string licenseNumber) {
            CozyComfortClient.DistributorServiceReference.UpdateDistributorProfileRequest inValue = new CozyComfortClient.DistributorServiceReference.UpdateDistributorProfileRequest();
            inValue.Body = new CozyComfortClient.DistributorServiceReference.UpdateDistributorProfileRequestBody();
            inValue.Body.distributorId = distributorId;
            inValue.Body.businessName = businessName;
            inValue.Body.contactNumber = contactNumber;
            inValue.Body.warehouseLocation = warehouseLocation;
            inValue.Body.licenseNumber = licenseNumber;
            return ((CozyComfortClient.DistributorServiceReference.DistributorServiceSoap)(this)).UpdateDistributorProfileAsync(inValue);
        }
    }
}
