//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CozyComfortClient.DInventoryServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DInventory", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DInventory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int DInventoryIDField;
        
        private int DistributorIDField;
        
        private int DBlanketIDField;
        
        private int DQuantityField;
        
        private System.DateTime DLastUpdatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int DInventoryID {
            get {
                return this.DInventoryIDField;
            }
            set {
                if ((this.DInventoryIDField.Equals(value) != true)) {
                    this.DInventoryIDField = value;
                    this.RaisePropertyChanged("DInventoryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int DistributorID {
            get {
                return this.DistributorIDField;
            }
            set {
                if ((this.DistributorIDField.Equals(value) != true)) {
                    this.DistributorIDField = value;
                    this.RaisePropertyChanged("DistributorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int DBlanketID {
            get {
                return this.DBlanketIDField;
            }
            set {
                if ((this.DBlanketIDField.Equals(value) != true)) {
                    this.DBlanketIDField = value;
                    this.RaisePropertyChanged("DBlanketID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int DQuantity {
            get {
                return this.DQuantityField;
            }
            set {
                if ((this.DQuantityField.Equals(value) != true)) {
                    this.DQuantityField = value;
                    this.RaisePropertyChanged("DQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime DLastUpdated {
            get {
                return this.DLastUpdatedField;
            }
            set {
                if ((this.DLastUpdatedField.Equals(value) != true)) {
                    this.DLastUpdatedField = value;
                    this.RaisePropertyChanged("DLastUpdated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DInventoryServiceReference.DInventoryServiceSoap")]
    public interface DInventoryServiceSoap {
        
        // CODEGEN: Generating message contract since element name inv from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddDInventory", ReplyAction="*")]
        CozyComfortClient.DInventoryServiceReference.AddDInventoryResponse AddDInventory(CozyComfortClient.DInventoryServiceReference.AddDInventoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddDInventory", ReplyAction="*")]
        System.Threading.Tasks.Task<CozyComfortClient.DInventoryServiceReference.AddDInventoryResponse> AddDInventoryAsync(CozyComfortClient.DInventoryServiceReference.AddDInventoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDistributorIdByAppUserId", ReplyAction="*")]
        int GetDistributorIdByAppUserId(int appUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDistributorIdByAppUserId", ReplyAction="*")]
        System.Threading.Tasks.Task<int> GetDistributorIdByAppUserIdAsync(int appUserId);
        
        // CODEGEN: Generating message contract since element name inv from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateDInventory", ReplyAction="*")]
        CozyComfortClient.DInventoryServiceReference.UpdateDInventoryResponse UpdateDInventory(CozyComfortClient.DInventoryServiceReference.UpdateDInventoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateDInventory", ReplyAction="*")]
        System.Threading.Tasks.Task<CozyComfortClient.DInventoryServiceReference.UpdateDInventoryResponse> UpdateDInventoryAsync(CozyComfortClient.DInventoryServiceReference.UpdateDInventoryRequest request);
        
        // CODEGEN: Generating message contract since element name DeleteDInventoryResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteDInventory", ReplyAction="*")]
        CozyComfortClient.DInventoryServiceReference.DeleteDInventoryResponse DeleteDInventory(CozyComfortClient.DInventoryServiceReference.DeleteDInventoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteDInventory", ReplyAction="*")]
        System.Threading.Tasks.Task<CozyComfortClient.DInventoryServiceReference.DeleteDInventoryResponse> DeleteDInventoryAsync(CozyComfortClient.DInventoryServiceReference.DeleteDInventoryRequest request);
        
        // CODEGEN: Generating message contract since element name ReduceInventoryResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReduceInventory", ReplyAction="*")]
        CozyComfortClient.DInventoryServiceReference.ReduceInventoryResponse ReduceInventory(CozyComfortClient.DInventoryServiceReference.ReduceInventoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReduceInventory", ReplyAction="*")]
        System.Threading.Tasks.Task<CozyComfortClient.DInventoryServiceReference.ReduceInventoryResponse> ReduceInventoryAsync(CozyComfortClient.DInventoryServiceReference.ReduceInventoryRequest request);
        
        // CODEGEN: Generating message contract since element name GetDInventoriesByDistributorResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDInventoriesByDistributor", ReplyAction="*")]
        CozyComfortClient.DInventoryServiceReference.GetDInventoriesByDistributorResponse GetDInventoriesByDistributor(CozyComfortClient.DInventoryServiceReference.GetDInventoriesByDistributorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDInventoriesByDistributor", ReplyAction="*")]
        System.Threading.Tasks.Task<CozyComfortClient.DInventoryServiceReference.GetDInventoriesByDistributorResponse> GetDInventoriesByDistributorAsync(CozyComfortClient.DInventoryServiceReference.GetDInventoriesByDistributorRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddDInventoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddDInventory", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.DInventoryServiceReference.AddDInventoryRequestBody Body;
        
        public AddDInventoryRequest() {
        }
        
        public AddDInventoryRequest(CozyComfortClient.DInventoryServiceReference.AddDInventoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddDInventoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CozyComfortClient.DInventoryServiceReference.DInventory inv;
        
        public AddDInventoryRequestBody() {
        }
        
        public AddDInventoryRequestBody(CozyComfortClient.DInventoryServiceReference.DInventory inv) {
            this.inv = inv;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddDInventoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddDInventoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.DInventoryServiceReference.AddDInventoryResponseBody Body;
        
        public AddDInventoryResponse() {
        }
        
        public AddDInventoryResponse(CozyComfortClient.DInventoryServiceReference.AddDInventoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddDInventoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddDInventoryResult;
        
        public AddDInventoryResponseBody() {
        }
        
        public AddDInventoryResponseBody(string AddDInventoryResult) {
            this.AddDInventoryResult = AddDInventoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateDInventoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateDInventory", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.DInventoryServiceReference.UpdateDInventoryRequestBody Body;
        
        public UpdateDInventoryRequest() {
        }
        
        public UpdateDInventoryRequest(CozyComfortClient.DInventoryServiceReference.UpdateDInventoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateDInventoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CozyComfortClient.DInventoryServiceReference.DInventory inv;
        
        public UpdateDInventoryRequestBody() {
        }
        
        public UpdateDInventoryRequestBody(CozyComfortClient.DInventoryServiceReference.DInventory inv) {
            this.inv = inv;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateDInventoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateDInventoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.DInventoryServiceReference.UpdateDInventoryResponseBody Body;
        
        public UpdateDInventoryResponse() {
        }
        
        public UpdateDInventoryResponse(CozyComfortClient.DInventoryServiceReference.UpdateDInventoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateDInventoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateDInventoryResult;
        
        public UpdateDInventoryResponseBody() {
        }
        
        public UpdateDInventoryResponseBody(string UpdateDInventoryResult) {
            this.UpdateDInventoryResult = UpdateDInventoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteDInventoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteDInventory", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.DInventoryServiceReference.DeleteDInventoryRequestBody Body;
        
        public DeleteDInventoryRequest() {
        }
        
        public DeleteDInventoryRequest(CozyComfortClient.DInventoryServiceReference.DeleteDInventoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteDInventoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int dInventoryId;
        
        public DeleteDInventoryRequestBody() {
        }
        
        public DeleteDInventoryRequestBody(int dInventoryId) {
            this.dInventoryId = dInventoryId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteDInventoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteDInventoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.DInventoryServiceReference.DeleteDInventoryResponseBody Body;
        
        public DeleteDInventoryResponse() {
        }
        
        public DeleteDInventoryResponse(CozyComfortClient.DInventoryServiceReference.DeleteDInventoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteDInventoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteDInventoryResult;
        
        public DeleteDInventoryResponseBody() {
        }
        
        public DeleteDInventoryResponseBody(string DeleteDInventoryResult) {
            this.DeleteDInventoryResult = DeleteDInventoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReduceInventoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReduceInventory", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.DInventoryServiceReference.ReduceInventoryRequestBody Body;
        
        public ReduceInventoryRequest() {
        }
        
        public ReduceInventoryRequest(CozyComfortClient.DInventoryServiceReference.ReduceInventoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReduceInventoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int blanketId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int quantity;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int distributorId;
        
        public ReduceInventoryRequestBody() {
        }
        
        public ReduceInventoryRequestBody(int blanketId, int quantity, int distributorId) {
            this.blanketId = blanketId;
            this.quantity = quantity;
            this.distributorId = distributorId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReduceInventoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReduceInventoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.DInventoryServiceReference.ReduceInventoryResponseBody Body;
        
        public ReduceInventoryResponse() {
        }
        
        public ReduceInventoryResponse(CozyComfortClient.DInventoryServiceReference.ReduceInventoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReduceInventoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ReduceInventoryResult;
        
        public ReduceInventoryResponseBody() {
        }
        
        public ReduceInventoryResponseBody(string ReduceInventoryResult) {
            this.ReduceInventoryResult = ReduceInventoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDInventoriesByDistributorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDInventoriesByDistributor", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.DInventoryServiceReference.GetDInventoriesByDistributorRequestBody Body;
        
        public GetDInventoriesByDistributorRequest() {
        }
        
        public GetDInventoriesByDistributorRequest(CozyComfortClient.DInventoryServiceReference.GetDInventoriesByDistributorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDInventoriesByDistributorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int distributorId;
        
        public GetDInventoriesByDistributorRequestBody() {
        }
        
        public GetDInventoriesByDistributorRequestBody(int distributorId) {
            this.distributorId = distributorId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDInventoriesByDistributorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDInventoriesByDistributorResponse", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.DInventoryServiceReference.GetDInventoriesByDistributorResponseBody Body;
        
        public GetDInventoriesByDistributorResponse() {
        }
        
        public GetDInventoriesByDistributorResponse(CozyComfortClient.DInventoryServiceReference.GetDInventoriesByDistributorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDInventoriesByDistributorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CozyComfortClient.DInventoryServiceReference.DInventory[] GetDInventoriesByDistributorResult;
        
        public GetDInventoriesByDistributorResponseBody() {
        }
        
        public GetDInventoriesByDistributorResponseBody(CozyComfortClient.DInventoryServiceReference.DInventory[] GetDInventoriesByDistributorResult) {
            this.GetDInventoriesByDistributorResult = GetDInventoriesByDistributorResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DInventoryServiceSoapChannel : CozyComfortClient.DInventoryServiceReference.DInventoryServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DInventoryServiceSoapClient : System.ServiceModel.ClientBase<CozyComfortClient.DInventoryServiceReference.DInventoryServiceSoap>, CozyComfortClient.DInventoryServiceReference.DInventoryServiceSoap {
        
        public DInventoryServiceSoapClient() {
        }
        
        public DInventoryServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DInventoryServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DInventoryServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DInventoryServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CozyComfortClient.DInventoryServiceReference.AddDInventoryResponse CozyComfortClient.DInventoryServiceReference.DInventoryServiceSoap.AddDInventory(CozyComfortClient.DInventoryServiceReference.AddDInventoryRequest request) {
            return base.Channel.AddDInventory(request);
        }
        
        public string AddDInventory(CozyComfortClient.DInventoryServiceReference.DInventory inv) {
            CozyComfortClient.DInventoryServiceReference.AddDInventoryRequest inValue = new CozyComfortClient.DInventoryServiceReference.AddDInventoryRequest();
            inValue.Body = new CozyComfortClient.DInventoryServiceReference.AddDInventoryRequestBody();
            inValue.Body.inv = inv;
            CozyComfortClient.DInventoryServiceReference.AddDInventoryResponse retVal = ((CozyComfortClient.DInventoryServiceReference.DInventoryServiceSoap)(this)).AddDInventory(inValue);
            return retVal.Body.AddDInventoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CozyComfortClient.DInventoryServiceReference.AddDInventoryResponse> CozyComfortClient.DInventoryServiceReference.DInventoryServiceSoap.AddDInventoryAsync(CozyComfortClient.DInventoryServiceReference.AddDInventoryRequest request) {
            return base.Channel.AddDInventoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<CozyComfortClient.DInventoryServiceReference.AddDInventoryResponse> AddDInventoryAsync(CozyComfortClient.DInventoryServiceReference.DInventory inv) {
            CozyComfortClient.DInventoryServiceReference.AddDInventoryRequest inValue = new CozyComfortClient.DInventoryServiceReference.AddDInventoryRequest();
            inValue.Body = new CozyComfortClient.DInventoryServiceReference.AddDInventoryRequestBody();
            inValue.Body.inv = inv;
            return ((CozyComfortClient.DInventoryServiceReference.DInventoryServiceSoap)(this)).AddDInventoryAsync(inValue);
        }
        
        public int GetDistributorIdByAppUserId(int appUserId) {
            return base.Channel.GetDistributorIdByAppUserId(appUserId);
        }
        
        public System.Threading.Tasks.Task<int> GetDistributorIdByAppUserIdAsync(int appUserId) {
            return base.Channel.GetDistributorIdByAppUserIdAsync(appUserId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CozyComfortClient.DInventoryServiceReference.UpdateDInventoryResponse CozyComfortClient.DInventoryServiceReference.DInventoryServiceSoap.UpdateDInventory(CozyComfortClient.DInventoryServiceReference.UpdateDInventoryRequest request) {
            return base.Channel.UpdateDInventory(request);
        }
        
        public string UpdateDInventory(CozyComfortClient.DInventoryServiceReference.DInventory inv) {
            CozyComfortClient.DInventoryServiceReference.UpdateDInventoryRequest inValue = new CozyComfortClient.DInventoryServiceReference.UpdateDInventoryRequest();
            inValue.Body = new CozyComfortClient.DInventoryServiceReference.UpdateDInventoryRequestBody();
            inValue.Body.inv = inv;
            CozyComfortClient.DInventoryServiceReference.UpdateDInventoryResponse retVal = ((CozyComfortClient.DInventoryServiceReference.DInventoryServiceSoap)(this)).UpdateDInventory(inValue);
            return retVal.Body.UpdateDInventoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CozyComfortClient.DInventoryServiceReference.UpdateDInventoryResponse> CozyComfortClient.DInventoryServiceReference.DInventoryServiceSoap.UpdateDInventoryAsync(CozyComfortClient.DInventoryServiceReference.UpdateDInventoryRequest request) {
            return base.Channel.UpdateDInventoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<CozyComfortClient.DInventoryServiceReference.UpdateDInventoryResponse> UpdateDInventoryAsync(CozyComfortClient.DInventoryServiceReference.DInventory inv) {
            CozyComfortClient.DInventoryServiceReference.UpdateDInventoryRequest inValue = new CozyComfortClient.DInventoryServiceReference.UpdateDInventoryRequest();
            inValue.Body = new CozyComfortClient.DInventoryServiceReference.UpdateDInventoryRequestBody();
            inValue.Body.inv = inv;
            return ((CozyComfortClient.DInventoryServiceReference.DInventoryServiceSoap)(this)).UpdateDInventoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CozyComfortClient.DInventoryServiceReference.DeleteDInventoryResponse CozyComfortClient.DInventoryServiceReference.DInventoryServiceSoap.DeleteDInventory(CozyComfortClient.DInventoryServiceReference.DeleteDInventoryRequest request) {
            return base.Channel.DeleteDInventory(request);
        }
        
        public string DeleteDInventory(int dInventoryId) {
            CozyComfortClient.DInventoryServiceReference.DeleteDInventoryRequest inValue = new CozyComfortClient.DInventoryServiceReference.DeleteDInventoryRequest();
            inValue.Body = new CozyComfortClient.DInventoryServiceReference.DeleteDInventoryRequestBody();
            inValue.Body.dInventoryId = dInventoryId;
            CozyComfortClient.DInventoryServiceReference.DeleteDInventoryResponse retVal = ((CozyComfortClient.DInventoryServiceReference.DInventoryServiceSoap)(this)).DeleteDInventory(inValue);
            return retVal.Body.DeleteDInventoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CozyComfortClient.DInventoryServiceReference.DeleteDInventoryResponse> CozyComfortClient.DInventoryServiceReference.DInventoryServiceSoap.DeleteDInventoryAsync(CozyComfortClient.DInventoryServiceReference.DeleteDInventoryRequest request) {
            return base.Channel.DeleteDInventoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<CozyComfortClient.DInventoryServiceReference.DeleteDInventoryResponse> DeleteDInventoryAsync(int dInventoryId) {
            CozyComfortClient.DInventoryServiceReference.DeleteDInventoryRequest inValue = new CozyComfortClient.DInventoryServiceReference.DeleteDInventoryRequest();
            inValue.Body = new CozyComfortClient.DInventoryServiceReference.DeleteDInventoryRequestBody();
            inValue.Body.dInventoryId = dInventoryId;
            return ((CozyComfortClient.DInventoryServiceReference.DInventoryServiceSoap)(this)).DeleteDInventoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CozyComfortClient.DInventoryServiceReference.ReduceInventoryResponse CozyComfortClient.DInventoryServiceReference.DInventoryServiceSoap.ReduceInventory(CozyComfortClient.DInventoryServiceReference.ReduceInventoryRequest request) {
            return base.Channel.ReduceInventory(request);
        }
        
        public string ReduceInventory(int blanketId, int quantity, int distributorId) {
            CozyComfortClient.DInventoryServiceReference.ReduceInventoryRequest inValue = new CozyComfortClient.DInventoryServiceReference.ReduceInventoryRequest();
            inValue.Body = new CozyComfortClient.DInventoryServiceReference.ReduceInventoryRequestBody();
            inValue.Body.blanketId = blanketId;
            inValue.Body.quantity = quantity;
            inValue.Body.distributorId = distributorId;
            CozyComfortClient.DInventoryServiceReference.ReduceInventoryResponse retVal = ((CozyComfortClient.DInventoryServiceReference.DInventoryServiceSoap)(this)).ReduceInventory(inValue);
            return retVal.Body.ReduceInventoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CozyComfortClient.DInventoryServiceReference.ReduceInventoryResponse> CozyComfortClient.DInventoryServiceReference.DInventoryServiceSoap.ReduceInventoryAsync(CozyComfortClient.DInventoryServiceReference.ReduceInventoryRequest request) {
            return base.Channel.ReduceInventoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<CozyComfortClient.DInventoryServiceReference.ReduceInventoryResponse> ReduceInventoryAsync(int blanketId, int quantity, int distributorId) {
            CozyComfortClient.DInventoryServiceReference.ReduceInventoryRequest inValue = new CozyComfortClient.DInventoryServiceReference.ReduceInventoryRequest();
            inValue.Body = new CozyComfortClient.DInventoryServiceReference.ReduceInventoryRequestBody();
            inValue.Body.blanketId = blanketId;
            inValue.Body.quantity = quantity;
            inValue.Body.distributorId = distributorId;
            return ((CozyComfortClient.DInventoryServiceReference.DInventoryServiceSoap)(this)).ReduceInventoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CozyComfortClient.DInventoryServiceReference.GetDInventoriesByDistributorResponse CozyComfortClient.DInventoryServiceReference.DInventoryServiceSoap.GetDInventoriesByDistributor(CozyComfortClient.DInventoryServiceReference.GetDInventoriesByDistributorRequest request) {
            return base.Channel.GetDInventoriesByDistributor(request);
        }
        
        public CozyComfortClient.DInventoryServiceReference.DInventory[] GetDInventoriesByDistributor(int distributorId) {
            CozyComfortClient.DInventoryServiceReference.GetDInventoriesByDistributorRequest inValue = new CozyComfortClient.DInventoryServiceReference.GetDInventoriesByDistributorRequest();
            inValue.Body = new CozyComfortClient.DInventoryServiceReference.GetDInventoriesByDistributorRequestBody();
            inValue.Body.distributorId = distributorId;
            CozyComfortClient.DInventoryServiceReference.GetDInventoriesByDistributorResponse retVal = ((CozyComfortClient.DInventoryServiceReference.DInventoryServiceSoap)(this)).GetDInventoriesByDistributor(inValue);
            return retVal.Body.GetDInventoriesByDistributorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CozyComfortClient.DInventoryServiceReference.GetDInventoriesByDistributorResponse> CozyComfortClient.DInventoryServiceReference.DInventoryServiceSoap.GetDInventoriesByDistributorAsync(CozyComfortClient.DInventoryServiceReference.GetDInventoriesByDistributorRequest request) {
            return base.Channel.GetDInventoriesByDistributorAsync(request);
        }
        
        public System.Threading.Tasks.Task<CozyComfortClient.DInventoryServiceReference.GetDInventoriesByDistributorResponse> GetDInventoriesByDistributorAsync(int distributorId) {
            CozyComfortClient.DInventoryServiceReference.GetDInventoriesByDistributorRequest inValue = new CozyComfortClient.DInventoryServiceReference.GetDInventoriesByDistributorRequest();
            inValue.Body = new CozyComfortClient.DInventoryServiceReference.GetDInventoriesByDistributorRequestBody();
            inValue.Body.distributorId = distributorId;
            return ((CozyComfortClient.DInventoryServiceReference.DInventoryServiceSoap)(this)).GetDInventoriesByDistributorAsync(inValue);
        }
    }
}
