//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CozyComfortClient.SOrderServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderOperationResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class OrderOperationResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        private int OrderIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((this.OrderIdField.Equals(value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SOrderDetails", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SOrderDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int OrderIdField;
        
        private int SellerIdField;
        
        private int DistributorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistributorNameField;
        
        private int BlanketIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BlanketModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BlanketMaterialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StoreNameField;
        
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        private System.DateTime OrderDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((this.OrderIdField.Equals(value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SellerId {
            get {
                return this.SellerIdField;
            }
            set {
                if ((this.SellerIdField.Equals(value) != true)) {
                    this.SellerIdField = value;
                    this.RaisePropertyChanged("SellerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int DistributorId {
            get {
                return this.DistributorIdField;
            }
            set {
                if ((this.DistributorIdField.Equals(value) != true)) {
                    this.DistributorIdField = value;
                    this.RaisePropertyChanged("DistributorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string DistributorName {
            get {
                return this.DistributorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DistributorNameField, value) != true)) {
                    this.DistributorNameField = value;
                    this.RaisePropertyChanged("DistributorName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int BlanketId {
            get {
                return this.BlanketIdField;
            }
            set {
                if ((this.BlanketIdField.Equals(value) != true)) {
                    this.BlanketIdField = value;
                    this.RaisePropertyChanged("BlanketId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string BlanketModel {
            get {
                return this.BlanketModelField;
            }
            set {
                if ((object.ReferenceEquals(this.BlanketModelField, value) != true)) {
                    this.BlanketModelField = value;
                    this.RaisePropertyChanged("BlanketModel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string BlanketMaterial {
            get {
                return this.BlanketMaterialField;
            }
            set {
                if ((object.ReferenceEquals(this.BlanketMaterialField, value) != true)) {
                    this.BlanketMaterialField = value;
                    this.RaisePropertyChanged("BlanketMaterial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string StoreName {
            get {
                return this.StoreNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StoreNameField, value) != true)) {
                    this.StoreNameField = value;
                    this.RaisePropertyChanged("StoreName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.DateTime OrderDate {
            get {
                return this.OrderDateField;
            }
            set {
                if ((this.OrderDateField.Equals(value) != true)) {
                    this.OrderDateField = value;
                    this.RaisePropertyChanged("OrderDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DistributorBlanket", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DistributorBlanket : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int DistributorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistributorNameField;
        
        private int AvailableQuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int DistributorId {
            get {
                return this.DistributorIdField;
            }
            set {
                if ((this.DistributorIdField.Equals(value) != true)) {
                    this.DistributorIdField = value;
                    this.RaisePropertyChanged("DistributorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string DistributorName {
            get {
                return this.DistributorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DistributorNameField, value) != true)) {
                    this.DistributorNameField = value;
                    this.RaisePropertyChanged("DistributorName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int AvailableQuantity {
            get {
                return this.AvailableQuantityField;
            }
            set {
                if ((this.AvailableQuantityField.Equals(value) != true)) {
                    this.AvailableQuantityField = value;
                    this.RaisePropertyChanged("AvailableQuantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SOrderServiceReference.SOrderServiceSoap")]
    public interface SOrderServiceSoap {
        
        // CODEGEN: Generating message contract since element name PlaceOrderResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PlaceOrder", ReplyAction="*")]
        CozyComfortClient.SOrderServiceReference.PlaceOrderResponse PlaceOrder(CozyComfortClient.SOrderServiceReference.PlaceOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PlaceOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<CozyComfortClient.SOrderServiceReference.PlaceOrderResponse> PlaceOrderAsync(CozyComfortClient.SOrderServiceReference.PlaceOrderRequest request);
        
        // CODEGEN: Generating message contract since element name newStatus from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateOrderStatus", ReplyAction="*")]
        CozyComfortClient.SOrderServiceReference.UpdateOrderStatusResponse UpdateOrderStatus(CozyComfortClient.SOrderServiceReference.UpdateOrderStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateOrderStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<CozyComfortClient.SOrderServiceReference.UpdateOrderStatusResponse> UpdateOrderStatusAsync(CozyComfortClient.SOrderServiceReference.UpdateOrderStatusRequest request);
        
        // CODEGEN: Generating message contract since element name CancelOrderResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CancelOrder", ReplyAction="*")]
        CozyComfortClient.SOrderServiceReference.CancelOrderResponse CancelOrder(CozyComfortClient.SOrderServiceReference.CancelOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CancelOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<CozyComfortClient.SOrderServiceReference.CancelOrderResponse> CancelOrderAsync(CozyComfortClient.SOrderServiceReference.CancelOrderRequest request);
        
        // CODEGEN: Generating message contract since element name GetOrderDetailsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrderDetails", ReplyAction="*")]
        CozyComfortClient.SOrderServiceReference.GetOrderDetailsResponse GetOrderDetails(CozyComfortClient.SOrderServiceReference.GetOrderDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrderDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<CozyComfortClient.SOrderServiceReference.GetOrderDetailsResponse> GetOrderDetailsAsync(CozyComfortClient.SOrderServiceReference.GetOrderDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name statusFilter from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrdersBySeller", ReplyAction="*")]
        CozyComfortClient.SOrderServiceReference.GetOrdersBySellerResponse GetOrdersBySeller(CozyComfortClient.SOrderServiceReference.GetOrdersBySellerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrdersBySeller", ReplyAction="*")]
        System.Threading.Tasks.Task<CozyComfortClient.SOrderServiceReference.GetOrdersBySellerResponse> GetOrdersBySellerAsync(CozyComfortClient.SOrderServiceReference.GetOrdersBySellerRequest request);
        
        // CODEGEN: Generating message contract since element name statusFilter from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrdersByDistributor", ReplyAction="*")]
        CozyComfortClient.SOrderServiceReference.GetOrdersByDistributorResponse GetOrdersByDistributor(CozyComfortClient.SOrderServiceReference.GetOrdersByDistributorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrdersByDistributor", ReplyAction="*")]
        System.Threading.Tasks.Task<CozyComfortClient.SOrderServiceReference.GetOrdersByDistributorResponse> GetOrdersByDistributorAsync(CozyComfortClient.SOrderServiceReference.GetOrdersByDistributorRequest request);
        
        // CODEGEN: Generating message contract since element name GetDistributorsForBlanketResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDistributorsForBlanket", ReplyAction="*")]
        CozyComfortClient.SOrderServiceReference.GetDistributorsForBlanketResponse GetDistributorsForBlanket(CozyComfortClient.SOrderServiceReference.GetDistributorsForBlanketRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDistributorsForBlanket", ReplyAction="*")]
        System.Threading.Tasks.Task<CozyComfortClient.SOrderServiceReference.GetDistributorsForBlanketResponse> GetDistributorsForBlanketAsync(CozyComfortClient.SOrderServiceReference.GetDistributorsForBlanketRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PlaceOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PlaceOrder", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.SOrderServiceReference.PlaceOrderRequestBody Body;
        
        public PlaceOrderRequest() {
        }
        
        public PlaceOrderRequest(CozyComfortClient.SOrderServiceReference.PlaceOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PlaceOrderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int sellerId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int distributorId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int blanketId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int quantity;
        
        public PlaceOrderRequestBody() {
        }
        
        public PlaceOrderRequestBody(int sellerId, int distributorId, int blanketId, int quantity) {
            this.sellerId = sellerId;
            this.distributorId = distributorId;
            this.blanketId = blanketId;
            this.quantity = quantity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PlaceOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PlaceOrderResponse", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.SOrderServiceReference.PlaceOrderResponseBody Body;
        
        public PlaceOrderResponse() {
        }
        
        public PlaceOrderResponse(CozyComfortClient.SOrderServiceReference.PlaceOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PlaceOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CozyComfortClient.SOrderServiceReference.OrderOperationResult PlaceOrderResult;
        
        public PlaceOrderResponseBody() {
        }
        
        public PlaceOrderResponseBody(CozyComfortClient.SOrderServiceReference.OrderOperationResult PlaceOrderResult) {
            this.PlaceOrderResult = PlaceOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateOrderStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateOrderStatus", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.SOrderServiceReference.UpdateOrderStatusRequestBody Body;
        
        public UpdateOrderStatusRequest() {
        }
        
        public UpdateOrderStatusRequest(CozyComfortClient.SOrderServiceReference.UpdateOrderStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateOrderStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string newStatus;
        
        public UpdateOrderStatusRequestBody() {
        }
        
        public UpdateOrderStatusRequestBody(int orderId, string newStatus) {
            this.orderId = orderId;
            this.newStatus = newStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateOrderStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateOrderStatusResponse", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.SOrderServiceReference.UpdateOrderStatusResponseBody Body;
        
        public UpdateOrderStatusResponse() {
        }
        
        public UpdateOrderStatusResponse(CozyComfortClient.SOrderServiceReference.UpdateOrderStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateOrderStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CozyComfortClient.SOrderServiceReference.OrderOperationResult UpdateOrderStatusResult;
        
        public UpdateOrderStatusResponseBody() {
        }
        
        public UpdateOrderStatusResponseBody(CozyComfortClient.SOrderServiceReference.OrderOperationResult UpdateOrderStatusResult) {
            this.UpdateOrderStatusResult = UpdateOrderStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelOrder", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.SOrderServiceReference.CancelOrderRequestBody Body;
        
        public CancelOrderRequest() {
        }
        
        public CancelOrderRequest(CozyComfortClient.SOrderServiceReference.CancelOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CancelOrderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int orderId;
        
        public CancelOrderRequestBody() {
        }
        
        public CancelOrderRequestBody(int orderId) {
            this.orderId = orderId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelOrderResponse", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.SOrderServiceReference.CancelOrderResponseBody Body;
        
        public CancelOrderResponse() {
        }
        
        public CancelOrderResponse(CozyComfortClient.SOrderServiceReference.CancelOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CancelOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CozyComfortClient.SOrderServiceReference.OrderOperationResult CancelOrderResult;
        
        public CancelOrderResponseBody() {
        }
        
        public CancelOrderResponseBody(CozyComfortClient.SOrderServiceReference.OrderOperationResult CancelOrderResult) {
            this.CancelOrderResult = CancelOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrderDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrderDetails", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.SOrderServiceReference.GetOrderDetailsRequestBody Body;
        
        public GetOrderDetailsRequest() {
        }
        
        public GetOrderDetailsRequest(CozyComfortClient.SOrderServiceReference.GetOrderDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOrderDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int orderId;
        
        public GetOrderDetailsRequestBody() {
        }
        
        public GetOrderDetailsRequestBody(int orderId) {
            this.orderId = orderId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrderDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrderDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.SOrderServiceReference.GetOrderDetailsResponseBody Body;
        
        public GetOrderDetailsResponse() {
        }
        
        public GetOrderDetailsResponse(CozyComfortClient.SOrderServiceReference.GetOrderDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOrderDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CozyComfortClient.SOrderServiceReference.SOrderDetails GetOrderDetailsResult;
        
        public GetOrderDetailsResponseBody() {
        }
        
        public GetOrderDetailsResponseBody(CozyComfortClient.SOrderServiceReference.SOrderDetails GetOrderDetailsResult) {
            this.GetOrderDetailsResult = GetOrderDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrdersBySellerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrdersBySeller", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.SOrderServiceReference.GetOrdersBySellerRequestBody Body;
        
        public GetOrdersBySellerRequest() {
        }
        
        public GetOrdersBySellerRequest(CozyComfortClient.SOrderServiceReference.GetOrdersBySellerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOrdersBySellerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int sellerId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string statusFilter;
        
        public GetOrdersBySellerRequestBody() {
        }
        
        public GetOrdersBySellerRequestBody(int sellerId, string statusFilter) {
            this.sellerId = sellerId;
            this.statusFilter = statusFilter;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrdersBySellerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrdersBySellerResponse", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.SOrderServiceReference.GetOrdersBySellerResponseBody Body;
        
        public GetOrdersBySellerResponse() {
        }
        
        public GetOrdersBySellerResponse(CozyComfortClient.SOrderServiceReference.GetOrdersBySellerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOrdersBySellerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CozyComfortClient.SOrderServiceReference.SOrderDetails[] GetOrdersBySellerResult;
        
        public GetOrdersBySellerResponseBody() {
        }
        
        public GetOrdersBySellerResponseBody(CozyComfortClient.SOrderServiceReference.SOrderDetails[] GetOrdersBySellerResult) {
            this.GetOrdersBySellerResult = GetOrdersBySellerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrdersByDistributorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrdersByDistributor", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.SOrderServiceReference.GetOrdersByDistributorRequestBody Body;
        
        public GetOrdersByDistributorRequest() {
        }
        
        public GetOrdersByDistributorRequest(CozyComfortClient.SOrderServiceReference.GetOrdersByDistributorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOrdersByDistributorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int distributorId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string statusFilter;
        
        public GetOrdersByDistributorRequestBody() {
        }
        
        public GetOrdersByDistributorRequestBody(int distributorId, string statusFilter) {
            this.distributorId = distributorId;
            this.statusFilter = statusFilter;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrdersByDistributorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrdersByDistributorResponse", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.SOrderServiceReference.GetOrdersByDistributorResponseBody Body;
        
        public GetOrdersByDistributorResponse() {
        }
        
        public GetOrdersByDistributorResponse(CozyComfortClient.SOrderServiceReference.GetOrdersByDistributorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOrdersByDistributorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CozyComfortClient.SOrderServiceReference.SOrderDetails[] GetOrdersByDistributorResult;
        
        public GetOrdersByDistributorResponseBody() {
        }
        
        public GetOrdersByDistributorResponseBody(CozyComfortClient.SOrderServiceReference.SOrderDetails[] GetOrdersByDistributorResult) {
            this.GetOrdersByDistributorResult = GetOrdersByDistributorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDistributorsForBlanketRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDistributorsForBlanket", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.SOrderServiceReference.GetDistributorsForBlanketRequestBody Body;
        
        public GetDistributorsForBlanketRequest() {
        }
        
        public GetDistributorsForBlanketRequest(CozyComfortClient.SOrderServiceReference.GetDistributorsForBlanketRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDistributorsForBlanketRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int blanketId;
        
        public GetDistributorsForBlanketRequestBody() {
        }
        
        public GetDistributorsForBlanketRequestBody(int blanketId) {
            this.blanketId = blanketId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDistributorsForBlanketResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDistributorsForBlanketResponse", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.SOrderServiceReference.GetDistributorsForBlanketResponseBody Body;
        
        public GetDistributorsForBlanketResponse() {
        }
        
        public GetDistributorsForBlanketResponse(CozyComfortClient.SOrderServiceReference.GetDistributorsForBlanketResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDistributorsForBlanketResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CozyComfortClient.SOrderServiceReference.DistributorBlanket[] GetDistributorsForBlanketResult;
        
        public GetDistributorsForBlanketResponseBody() {
        }
        
        public GetDistributorsForBlanketResponseBody(CozyComfortClient.SOrderServiceReference.DistributorBlanket[] GetDistributorsForBlanketResult) {
            this.GetDistributorsForBlanketResult = GetDistributorsForBlanketResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SOrderServiceSoapChannel : CozyComfortClient.SOrderServiceReference.SOrderServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SOrderServiceSoapClient : System.ServiceModel.ClientBase<CozyComfortClient.SOrderServiceReference.SOrderServiceSoap>, CozyComfortClient.SOrderServiceReference.SOrderServiceSoap {
        
        public SOrderServiceSoapClient() {
        }
        
        public SOrderServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SOrderServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SOrderServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SOrderServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CozyComfortClient.SOrderServiceReference.PlaceOrderResponse CozyComfortClient.SOrderServiceReference.SOrderServiceSoap.PlaceOrder(CozyComfortClient.SOrderServiceReference.PlaceOrderRequest request) {
            return base.Channel.PlaceOrder(request);
        }
        
        public CozyComfortClient.SOrderServiceReference.OrderOperationResult PlaceOrder(int sellerId, int distributorId, int blanketId, int quantity) {
            CozyComfortClient.SOrderServiceReference.PlaceOrderRequest inValue = new CozyComfortClient.SOrderServiceReference.PlaceOrderRequest();
            inValue.Body = new CozyComfortClient.SOrderServiceReference.PlaceOrderRequestBody();
            inValue.Body.sellerId = sellerId;
            inValue.Body.distributorId = distributorId;
            inValue.Body.blanketId = blanketId;
            inValue.Body.quantity = quantity;
            CozyComfortClient.SOrderServiceReference.PlaceOrderResponse retVal = ((CozyComfortClient.SOrderServiceReference.SOrderServiceSoap)(this)).PlaceOrder(inValue);
            return retVal.Body.PlaceOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CozyComfortClient.SOrderServiceReference.PlaceOrderResponse> CozyComfortClient.SOrderServiceReference.SOrderServiceSoap.PlaceOrderAsync(CozyComfortClient.SOrderServiceReference.PlaceOrderRequest request) {
            return base.Channel.PlaceOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<CozyComfortClient.SOrderServiceReference.PlaceOrderResponse> PlaceOrderAsync(int sellerId, int distributorId, int blanketId, int quantity) {
            CozyComfortClient.SOrderServiceReference.PlaceOrderRequest inValue = new CozyComfortClient.SOrderServiceReference.PlaceOrderRequest();
            inValue.Body = new CozyComfortClient.SOrderServiceReference.PlaceOrderRequestBody();
            inValue.Body.sellerId = sellerId;
            inValue.Body.distributorId = distributorId;
            inValue.Body.blanketId = blanketId;
            inValue.Body.quantity = quantity;
            return ((CozyComfortClient.SOrderServiceReference.SOrderServiceSoap)(this)).PlaceOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CozyComfortClient.SOrderServiceReference.UpdateOrderStatusResponse CozyComfortClient.SOrderServiceReference.SOrderServiceSoap.UpdateOrderStatus(CozyComfortClient.SOrderServiceReference.UpdateOrderStatusRequest request) {
            return base.Channel.UpdateOrderStatus(request);
        }
        
        public CozyComfortClient.SOrderServiceReference.OrderOperationResult UpdateOrderStatus(int orderId, string newStatus) {
            CozyComfortClient.SOrderServiceReference.UpdateOrderStatusRequest inValue = new CozyComfortClient.SOrderServiceReference.UpdateOrderStatusRequest();
            inValue.Body = new CozyComfortClient.SOrderServiceReference.UpdateOrderStatusRequestBody();
            inValue.Body.orderId = orderId;
            inValue.Body.newStatus = newStatus;
            CozyComfortClient.SOrderServiceReference.UpdateOrderStatusResponse retVal = ((CozyComfortClient.SOrderServiceReference.SOrderServiceSoap)(this)).UpdateOrderStatus(inValue);
            return retVal.Body.UpdateOrderStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CozyComfortClient.SOrderServiceReference.UpdateOrderStatusResponse> CozyComfortClient.SOrderServiceReference.SOrderServiceSoap.UpdateOrderStatusAsync(CozyComfortClient.SOrderServiceReference.UpdateOrderStatusRequest request) {
            return base.Channel.UpdateOrderStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<CozyComfortClient.SOrderServiceReference.UpdateOrderStatusResponse> UpdateOrderStatusAsync(int orderId, string newStatus) {
            CozyComfortClient.SOrderServiceReference.UpdateOrderStatusRequest inValue = new CozyComfortClient.SOrderServiceReference.UpdateOrderStatusRequest();
            inValue.Body = new CozyComfortClient.SOrderServiceReference.UpdateOrderStatusRequestBody();
            inValue.Body.orderId = orderId;
            inValue.Body.newStatus = newStatus;
            return ((CozyComfortClient.SOrderServiceReference.SOrderServiceSoap)(this)).UpdateOrderStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CozyComfortClient.SOrderServiceReference.CancelOrderResponse CozyComfortClient.SOrderServiceReference.SOrderServiceSoap.CancelOrder(CozyComfortClient.SOrderServiceReference.CancelOrderRequest request) {
            return base.Channel.CancelOrder(request);
        }
        
        public CozyComfortClient.SOrderServiceReference.OrderOperationResult CancelOrder(int orderId) {
            CozyComfortClient.SOrderServiceReference.CancelOrderRequest inValue = new CozyComfortClient.SOrderServiceReference.CancelOrderRequest();
            inValue.Body = new CozyComfortClient.SOrderServiceReference.CancelOrderRequestBody();
            inValue.Body.orderId = orderId;
            CozyComfortClient.SOrderServiceReference.CancelOrderResponse retVal = ((CozyComfortClient.SOrderServiceReference.SOrderServiceSoap)(this)).CancelOrder(inValue);
            return retVal.Body.CancelOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CozyComfortClient.SOrderServiceReference.CancelOrderResponse> CozyComfortClient.SOrderServiceReference.SOrderServiceSoap.CancelOrderAsync(CozyComfortClient.SOrderServiceReference.CancelOrderRequest request) {
            return base.Channel.CancelOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<CozyComfortClient.SOrderServiceReference.CancelOrderResponse> CancelOrderAsync(int orderId) {
            CozyComfortClient.SOrderServiceReference.CancelOrderRequest inValue = new CozyComfortClient.SOrderServiceReference.CancelOrderRequest();
            inValue.Body = new CozyComfortClient.SOrderServiceReference.CancelOrderRequestBody();
            inValue.Body.orderId = orderId;
            return ((CozyComfortClient.SOrderServiceReference.SOrderServiceSoap)(this)).CancelOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CozyComfortClient.SOrderServiceReference.GetOrderDetailsResponse CozyComfortClient.SOrderServiceReference.SOrderServiceSoap.GetOrderDetails(CozyComfortClient.SOrderServiceReference.GetOrderDetailsRequest request) {
            return base.Channel.GetOrderDetails(request);
        }
        
        public CozyComfortClient.SOrderServiceReference.SOrderDetails GetOrderDetails(int orderId) {
            CozyComfortClient.SOrderServiceReference.GetOrderDetailsRequest inValue = new CozyComfortClient.SOrderServiceReference.GetOrderDetailsRequest();
            inValue.Body = new CozyComfortClient.SOrderServiceReference.GetOrderDetailsRequestBody();
            inValue.Body.orderId = orderId;
            CozyComfortClient.SOrderServiceReference.GetOrderDetailsResponse retVal = ((CozyComfortClient.SOrderServiceReference.SOrderServiceSoap)(this)).GetOrderDetails(inValue);
            return retVal.Body.GetOrderDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CozyComfortClient.SOrderServiceReference.GetOrderDetailsResponse> CozyComfortClient.SOrderServiceReference.SOrderServiceSoap.GetOrderDetailsAsync(CozyComfortClient.SOrderServiceReference.GetOrderDetailsRequest request) {
            return base.Channel.GetOrderDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<CozyComfortClient.SOrderServiceReference.GetOrderDetailsResponse> GetOrderDetailsAsync(int orderId) {
            CozyComfortClient.SOrderServiceReference.GetOrderDetailsRequest inValue = new CozyComfortClient.SOrderServiceReference.GetOrderDetailsRequest();
            inValue.Body = new CozyComfortClient.SOrderServiceReference.GetOrderDetailsRequestBody();
            inValue.Body.orderId = orderId;
            return ((CozyComfortClient.SOrderServiceReference.SOrderServiceSoap)(this)).GetOrderDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CozyComfortClient.SOrderServiceReference.GetOrdersBySellerResponse CozyComfortClient.SOrderServiceReference.SOrderServiceSoap.GetOrdersBySeller(CozyComfortClient.SOrderServiceReference.GetOrdersBySellerRequest request) {
            return base.Channel.GetOrdersBySeller(request);
        }
        
        public CozyComfortClient.SOrderServiceReference.SOrderDetails[] GetOrdersBySeller(int sellerId, string statusFilter) {
            CozyComfortClient.SOrderServiceReference.GetOrdersBySellerRequest inValue = new CozyComfortClient.SOrderServiceReference.GetOrdersBySellerRequest();
            inValue.Body = new CozyComfortClient.SOrderServiceReference.GetOrdersBySellerRequestBody();
            inValue.Body.sellerId = sellerId;
            inValue.Body.statusFilter = statusFilter;
            CozyComfortClient.SOrderServiceReference.GetOrdersBySellerResponse retVal = ((CozyComfortClient.SOrderServiceReference.SOrderServiceSoap)(this)).GetOrdersBySeller(inValue);
            return retVal.Body.GetOrdersBySellerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CozyComfortClient.SOrderServiceReference.GetOrdersBySellerResponse> CozyComfortClient.SOrderServiceReference.SOrderServiceSoap.GetOrdersBySellerAsync(CozyComfortClient.SOrderServiceReference.GetOrdersBySellerRequest request) {
            return base.Channel.GetOrdersBySellerAsync(request);
        }
        
        public System.Threading.Tasks.Task<CozyComfortClient.SOrderServiceReference.GetOrdersBySellerResponse> GetOrdersBySellerAsync(int sellerId, string statusFilter) {
            CozyComfortClient.SOrderServiceReference.GetOrdersBySellerRequest inValue = new CozyComfortClient.SOrderServiceReference.GetOrdersBySellerRequest();
            inValue.Body = new CozyComfortClient.SOrderServiceReference.GetOrdersBySellerRequestBody();
            inValue.Body.sellerId = sellerId;
            inValue.Body.statusFilter = statusFilter;
            return ((CozyComfortClient.SOrderServiceReference.SOrderServiceSoap)(this)).GetOrdersBySellerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CozyComfortClient.SOrderServiceReference.GetOrdersByDistributorResponse CozyComfortClient.SOrderServiceReference.SOrderServiceSoap.GetOrdersByDistributor(CozyComfortClient.SOrderServiceReference.GetOrdersByDistributorRequest request) {
            return base.Channel.GetOrdersByDistributor(request);
        }
        
        public CozyComfortClient.SOrderServiceReference.SOrderDetails[] GetOrdersByDistributor(int distributorId, string statusFilter) {
            CozyComfortClient.SOrderServiceReference.GetOrdersByDistributorRequest inValue = new CozyComfortClient.SOrderServiceReference.GetOrdersByDistributorRequest();
            inValue.Body = new CozyComfortClient.SOrderServiceReference.GetOrdersByDistributorRequestBody();
            inValue.Body.distributorId = distributorId;
            inValue.Body.statusFilter = statusFilter;
            CozyComfortClient.SOrderServiceReference.GetOrdersByDistributorResponse retVal = ((CozyComfortClient.SOrderServiceReference.SOrderServiceSoap)(this)).GetOrdersByDistributor(inValue);
            return retVal.Body.GetOrdersByDistributorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CozyComfortClient.SOrderServiceReference.GetOrdersByDistributorResponse> CozyComfortClient.SOrderServiceReference.SOrderServiceSoap.GetOrdersByDistributorAsync(CozyComfortClient.SOrderServiceReference.GetOrdersByDistributorRequest request) {
            return base.Channel.GetOrdersByDistributorAsync(request);
        }
        
        public System.Threading.Tasks.Task<CozyComfortClient.SOrderServiceReference.GetOrdersByDistributorResponse> GetOrdersByDistributorAsync(int distributorId, string statusFilter) {
            CozyComfortClient.SOrderServiceReference.GetOrdersByDistributorRequest inValue = new CozyComfortClient.SOrderServiceReference.GetOrdersByDistributorRequest();
            inValue.Body = new CozyComfortClient.SOrderServiceReference.GetOrdersByDistributorRequestBody();
            inValue.Body.distributorId = distributorId;
            inValue.Body.statusFilter = statusFilter;
            return ((CozyComfortClient.SOrderServiceReference.SOrderServiceSoap)(this)).GetOrdersByDistributorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CozyComfortClient.SOrderServiceReference.GetDistributorsForBlanketResponse CozyComfortClient.SOrderServiceReference.SOrderServiceSoap.GetDistributorsForBlanket(CozyComfortClient.SOrderServiceReference.GetDistributorsForBlanketRequest request) {
            return base.Channel.GetDistributorsForBlanket(request);
        }
        
        public CozyComfortClient.SOrderServiceReference.DistributorBlanket[] GetDistributorsForBlanket(int blanketId) {
            CozyComfortClient.SOrderServiceReference.GetDistributorsForBlanketRequest inValue = new CozyComfortClient.SOrderServiceReference.GetDistributorsForBlanketRequest();
            inValue.Body = new CozyComfortClient.SOrderServiceReference.GetDistributorsForBlanketRequestBody();
            inValue.Body.blanketId = blanketId;
            CozyComfortClient.SOrderServiceReference.GetDistributorsForBlanketResponse retVal = ((CozyComfortClient.SOrderServiceReference.SOrderServiceSoap)(this)).GetDistributorsForBlanket(inValue);
            return retVal.Body.GetDistributorsForBlanketResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CozyComfortClient.SOrderServiceReference.GetDistributorsForBlanketResponse> CozyComfortClient.SOrderServiceReference.SOrderServiceSoap.GetDistributorsForBlanketAsync(CozyComfortClient.SOrderServiceReference.GetDistributorsForBlanketRequest request) {
            return base.Channel.GetDistributorsForBlanketAsync(request);
        }
        
        public System.Threading.Tasks.Task<CozyComfortClient.SOrderServiceReference.GetDistributorsForBlanketResponse> GetDistributorsForBlanketAsync(int blanketId) {
            CozyComfortClient.SOrderServiceReference.GetDistributorsForBlanketRequest inValue = new CozyComfortClient.SOrderServiceReference.GetDistributorsForBlanketRequest();
            inValue.Body = new CozyComfortClient.SOrderServiceReference.GetDistributorsForBlanketRequestBody();
            inValue.Body.blanketId = blanketId;
            return ((CozyComfortClient.SOrderServiceReference.SOrderServiceSoap)(this)).GetDistributorsForBlanketAsync(inValue);
        }
    }
}
