//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CozyComfortClient.MInventoryServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MInventory", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class MInventory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int MInventoryIDField;
        
        private int ManufacturerIDField;
        
        private int MBlanketIDField;
        
        private int MQuantityField;
        
        private System.DateTime MLastUpdatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int MInventoryID {
            get {
                return this.MInventoryIDField;
            }
            set {
                if ((this.MInventoryIDField.Equals(value) != true)) {
                    this.MInventoryIDField = value;
                    this.RaisePropertyChanged("MInventoryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ManufacturerID {
            get {
                return this.ManufacturerIDField;
            }
            set {
                if ((this.ManufacturerIDField.Equals(value) != true)) {
                    this.ManufacturerIDField = value;
                    this.RaisePropertyChanged("ManufacturerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int MBlanketID {
            get {
                return this.MBlanketIDField;
            }
            set {
                if ((this.MBlanketIDField.Equals(value) != true)) {
                    this.MBlanketIDField = value;
                    this.RaisePropertyChanged("MBlanketID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int MQuantity {
            get {
                return this.MQuantityField;
            }
            set {
                if ((this.MQuantityField.Equals(value) != true)) {
                    this.MQuantityField = value;
                    this.RaisePropertyChanged("MQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime MLastUpdated {
            get {
                return this.MLastUpdatedField;
            }
            set {
                if ((this.MLastUpdatedField.Equals(value) != true)) {
                    this.MLastUpdatedField = value;
                    this.RaisePropertyChanged("MLastUpdated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MInventoryServiceReference.MInventoryServiceSoap")]
    public interface MInventoryServiceSoap {
        
        // CODEGEN: Generating message contract since element name inv from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddMInventory", ReplyAction="*")]
        CozyComfortClient.MInventoryServiceReference.AddMInventoryResponse AddMInventory(CozyComfortClient.MInventoryServiceReference.AddMInventoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddMInventory", ReplyAction="*")]
        System.Threading.Tasks.Task<CozyComfortClient.MInventoryServiceReference.AddMInventoryResponse> AddMInventoryAsync(CozyComfortClient.MInventoryServiceReference.AddMInventoryRequest request);
        
        // CODEGEN: Generating message contract since element name inv from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateMInventory", ReplyAction="*")]
        CozyComfortClient.MInventoryServiceReference.UpdateMInventoryResponse UpdateMInventory(CozyComfortClient.MInventoryServiceReference.UpdateMInventoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateMInventory", ReplyAction="*")]
        System.Threading.Tasks.Task<CozyComfortClient.MInventoryServiceReference.UpdateMInventoryResponse> UpdateMInventoryAsync(CozyComfortClient.MInventoryServiceReference.UpdateMInventoryRequest request);
        
        // CODEGEN: Generating message contract since element name DeleteMInventoryResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteMInventory", ReplyAction="*")]
        CozyComfortClient.MInventoryServiceReference.DeleteMInventoryResponse DeleteMInventory(CozyComfortClient.MInventoryServiceReference.DeleteMInventoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteMInventory", ReplyAction="*")]
        System.Threading.Tasks.Task<CozyComfortClient.MInventoryServiceReference.DeleteMInventoryResponse> DeleteMInventoryAsync(CozyComfortClient.MInventoryServiceReference.DeleteMInventoryRequest request);
        
        // CODEGEN: Generating message contract since element name GetMInventoriesByManufacturerResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMInventoriesByManufacturer", ReplyAction="*")]
        CozyComfortClient.MInventoryServiceReference.GetMInventoriesByManufacturerResponse GetMInventoriesByManufacturer(CozyComfortClient.MInventoryServiceReference.GetMInventoriesByManufacturerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMInventoriesByManufacturer", ReplyAction="*")]
        System.Threading.Tasks.Task<CozyComfortClient.MInventoryServiceReference.GetMInventoriesByManufacturerResponse> GetMInventoriesByManufacturerAsync(CozyComfortClient.MInventoryServiceReference.GetMInventoriesByManufacturerRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddMInventoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddMInventory", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.MInventoryServiceReference.AddMInventoryRequestBody Body;
        
        public AddMInventoryRequest() {
        }
        
        public AddMInventoryRequest(CozyComfortClient.MInventoryServiceReference.AddMInventoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddMInventoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CozyComfortClient.MInventoryServiceReference.MInventory inv;
        
        public AddMInventoryRequestBody() {
        }
        
        public AddMInventoryRequestBody(CozyComfortClient.MInventoryServiceReference.MInventory inv) {
            this.inv = inv;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddMInventoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddMInventoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.MInventoryServiceReference.AddMInventoryResponseBody Body;
        
        public AddMInventoryResponse() {
        }
        
        public AddMInventoryResponse(CozyComfortClient.MInventoryServiceReference.AddMInventoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddMInventoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddMInventoryResult;
        
        public AddMInventoryResponseBody() {
        }
        
        public AddMInventoryResponseBody(string AddMInventoryResult) {
            this.AddMInventoryResult = AddMInventoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateMInventoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateMInventory", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.MInventoryServiceReference.UpdateMInventoryRequestBody Body;
        
        public UpdateMInventoryRequest() {
        }
        
        public UpdateMInventoryRequest(CozyComfortClient.MInventoryServiceReference.UpdateMInventoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateMInventoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CozyComfortClient.MInventoryServiceReference.MInventory inv;
        
        public UpdateMInventoryRequestBody() {
        }
        
        public UpdateMInventoryRequestBody(CozyComfortClient.MInventoryServiceReference.MInventory inv) {
            this.inv = inv;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateMInventoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateMInventoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.MInventoryServiceReference.UpdateMInventoryResponseBody Body;
        
        public UpdateMInventoryResponse() {
        }
        
        public UpdateMInventoryResponse(CozyComfortClient.MInventoryServiceReference.UpdateMInventoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateMInventoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateMInventoryResult;
        
        public UpdateMInventoryResponseBody() {
        }
        
        public UpdateMInventoryResponseBody(string UpdateMInventoryResult) {
            this.UpdateMInventoryResult = UpdateMInventoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteMInventoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteMInventory", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.MInventoryServiceReference.DeleteMInventoryRequestBody Body;
        
        public DeleteMInventoryRequest() {
        }
        
        public DeleteMInventoryRequest(CozyComfortClient.MInventoryServiceReference.DeleteMInventoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteMInventoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int mInventoryId;
        
        public DeleteMInventoryRequestBody() {
        }
        
        public DeleteMInventoryRequestBody(int mInventoryId) {
            this.mInventoryId = mInventoryId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteMInventoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteMInventoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.MInventoryServiceReference.DeleteMInventoryResponseBody Body;
        
        public DeleteMInventoryResponse() {
        }
        
        public DeleteMInventoryResponse(CozyComfortClient.MInventoryServiceReference.DeleteMInventoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteMInventoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteMInventoryResult;
        
        public DeleteMInventoryResponseBody() {
        }
        
        public DeleteMInventoryResponseBody(string DeleteMInventoryResult) {
            this.DeleteMInventoryResult = DeleteMInventoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMInventoriesByManufacturerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMInventoriesByManufacturer", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.MInventoryServiceReference.GetMInventoriesByManufacturerRequestBody Body;
        
        public GetMInventoriesByManufacturerRequest() {
        }
        
        public GetMInventoriesByManufacturerRequest(CozyComfortClient.MInventoryServiceReference.GetMInventoriesByManufacturerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMInventoriesByManufacturerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int manufacturerId;
        
        public GetMInventoriesByManufacturerRequestBody() {
        }
        
        public GetMInventoriesByManufacturerRequestBody(int manufacturerId) {
            this.manufacturerId = manufacturerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMInventoriesByManufacturerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMInventoriesByManufacturerResponse", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.MInventoryServiceReference.GetMInventoriesByManufacturerResponseBody Body;
        
        public GetMInventoriesByManufacturerResponse() {
        }
        
        public GetMInventoriesByManufacturerResponse(CozyComfortClient.MInventoryServiceReference.GetMInventoriesByManufacturerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMInventoriesByManufacturerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CozyComfortClient.MInventoryServiceReference.MInventory[] GetMInventoriesByManufacturerResult;
        
        public GetMInventoriesByManufacturerResponseBody() {
        }
        
        public GetMInventoriesByManufacturerResponseBody(CozyComfortClient.MInventoryServiceReference.MInventory[] GetMInventoriesByManufacturerResult) {
            this.GetMInventoriesByManufacturerResult = GetMInventoriesByManufacturerResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MInventoryServiceSoapChannel : CozyComfortClient.MInventoryServiceReference.MInventoryServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MInventoryServiceSoapClient : System.ServiceModel.ClientBase<CozyComfortClient.MInventoryServiceReference.MInventoryServiceSoap>, CozyComfortClient.MInventoryServiceReference.MInventoryServiceSoap {
        
        public MInventoryServiceSoapClient() {
        }
        
        public MInventoryServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MInventoryServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MInventoryServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MInventoryServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CozyComfortClient.MInventoryServiceReference.AddMInventoryResponse CozyComfortClient.MInventoryServiceReference.MInventoryServiceSoap.AddMInventory(CozyComfortClient.MInventoryServiceReference.AddMInventoryRequest request) {
            return base.Channel.AddMInventory(request);
        }
        
        public string AddMInventory(CozyComfortClient.MInventoryServiceReference.MInventory inv) {
            CozyComfortClient.MInventoryServiceReference.AddMInventoryRequest inValue = new CozyComfortClient.MInventoryServiceReference.AddMInventoryRequest();
            inValue.Body = new CozyComfortClient.MInventoryServiceReference.AddMInventoryRequestBody();
            inValue.Body.inv = inv;
            CozyComfortClient.MInventoryServiceReference.AddMInventoryResponse retVal = ((CozyComfortClient.MInventoryServiceReference.MInventoryServiceSoap)(this)).AddMInventory(inValue);
            return retVal.Body.AddMInventoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CozyComfortClient.MInventoryServiceReference.AddMInventoryResponse> CozyComfortClient.MInventoryServiceReference.MInventoryServiceSoap.AddMInventoryAsync(CozyComfortClient.MInventoryServiceReference.AddMInventoryRequest request) {
            return base.Channel.AddMInventoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<CozyComfortClient.MInventoryServiceReference.AddMInventoryResponse> AddMInventoryAsync(CozyComfortClient.MInventoryServiceReference.MInventory inv) {
            CozyComfortClient.MInventoryServiceReference.AddMInventoryRequest inValue = new CozyComfortClient.MInventoryServiceReference.AddMInventoryRequest();
            inValue.Body = new CozyComfortClient.MInventoryServiceReference.AddMInventoryRequestBody();
            inValue.Body.inv = inv;
            return ((CozyComfortClient.MInventoryServiceReference.MInventoryServiceSoap)(this)).AddMInventoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CozyComfortClient.MInventoryServiceReference.UpdateMInventoryResponse CozyComfortClient.MInventoryServiceReference.MInventoryServiceSoap.UpdateMInventory(CozyComfortClient.MInventoryServiceReference.UpdateMInventoryRequest request) {
            return base.Channel.UpdateMInventory(request);
        }
        
        public string UpdateMInventory(CozyComfortClient.MInventoryServiceReference.MInventory inv) {
            CozyComfortClient.MInventoryServiceReference.UpdateMInventoryRequest inValue = new CozyComfortClient.MInventoryServiceReference.UpdateMInventoryRequest();
            inValue.Body = new CozyComfortClient.MInventoryServiceReference.UpdateMInventoryRequestBody();
            inValue.Body.inv = inv;
            CozyComfortClient.MInventoryServiceReference.UpdateMInventoryResponse retVal = ((CozyComfortClient.MInventoryServiceReference.MInventoryServiceSoap)(this)).UpdateMInventory(inValue);
            return retVal.Body.UpdateMInventoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CozyComfortClient.MInventoryServiceReference.UpdateMInventoryResponse> CozyComfortClient.MInventoryServiceReference.MInventoryServiceSoap.UpdateMInventoryAsync(CozyComfortClient.MInventoryServiceReference.UpdateMInventoryRequest request) {
            return base.Channel.UpdateMInventoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<CozyComfortClient.MInventoryServiceReference.UpdateMInventoryResponse> UpdateMInventoryAsync(CozyComfortClient.MInventoryServiceReference.MInventory inv) {
            CozyComfortClient.MInventoryServiceReference.UpdateMInventoryRequest inValue = new CozyComfortClient.MInventoryServiceReference.UpdateMInventoryRequest();
            inValue.Body = new CozyComfortClient.MInventoryServiceReference.UpdateMInventoryRequestBody();
            inValue.Body.inv = inv;
            return ((CozyComfortClient.MInventoryServiceReference.MInventoryServiceSoap)(this)).UpdateMInventoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CozyComfortClient.MInventoryServiceReference.DeleteMInventoryResponse CozyComfortClient.MInventoryServiceReference.MInventoryServiceSoap.DeleteMInventory(CozyComfortClient.MInventoryServiceReference.DeleteMInventoryRequest request) {
            return base.Channel.DeleteMInventory(request);
        }
        
        public string DeleteMInventory(int mInventoryId) {
            CozyComfortClient.MInventoryServiceReference.DeleteMInventoryRequest inValue = new CozyComfortClient.MInventoryServiceReference.DeleteMInventoryRequest();
            inValue.Body = new CozyComfortClient.MInventoryServiceReference.DeleteMInventoryRequestBody();
            inValue.Body.mInventoryId = mInventoryId;
            CozyComfortClient.MInventoryServiceReference.DeleteMInventoryResponse retVal = ((CozyComfortClient.MInventoryServiceReference.MInventoryServiceSoap)(this)).DeleteMInventory(inValue);
            return retVal.Body.DeleteMInventoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CozyComfortClient.MInventoryServiceReference.DeleteMInventoryResponse> CozyComfortClient.MInventoryServiceReference.MInventoryServiceSoap.DeleteMInventoryAsync(CozyComfortClient.MInventoryServiceReference.DeleteMInventoryRequest request) {
            return base.Channel.DeleteMInventoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<CozyComfortClient.MInventoryServiceReference.DeleteMInventoryResponse> DeleteMInventoryAsync(int mInventoryId) {
            CozyComfortClient.MInventoryServiceReference.DeleteMInventoryRequest inValue = new CozyComfortClient.MInventoryServiceReference.DeleteMInventoryRequest();
            inValue.Body = new CozyComfortClient.MInventoryServiceReference.DeleteMInventoryRequestBody();
            inValue.Body.mInventoryId = mInventoryId;
            return ((CozyComfortClient.MInventoryServiceReference.MInventoryServiceSoap)(this)).DeleteMInventoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CozyComfortClient.MInventoryServiceReference.GetMInventoriesByManufacturerResponse CozyComfortClient.MInventoryServiceReference.MInventoryServiceSoap.GetMInventoriesByManufacturer(CozyComfortClient.MInventoryServiceReference.GetMInventoriesByManufacturerRequest request) {
            return base.Channel.GetMInventoriesByManufacturer(request);
        }
        
        public CozyComfortClient.MInventoryServiceReference.MInventory[] GetMInventoriesByManufacturer(int manufacturerId) {
            CozyComfortClient.MInventoryServiceReference.GetMInventoriesByManufacturerRequest inValue = new CozyComfortClient.MInventoryServiceReference.GetMInventoriesByManufacturerRequest();
            inValue.Body = new CozyComfortClient.MInventoryServiceReference.GetMInventoriesByManufacturerRequestBody();
            inValue.Body.manufacturerId = manufacturerId;
            CozyComfortClient.MInventoryServiceReference.GetMInventoriesByManufacturerResponse retVal = ((CozyComfortClient.MInventoryServiceReference.MInventoryServiceSoap)(this)).GetMInventoriesByManufacturer(inValue);
            return retVal.Body.GetMInventoriesByManufacturerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CozyComfortClient.MInventoryServiceReference.GetMInventoriesByManufacturerResponse> CozyComfortClient.MInventoryServiceReference.MInventoryServiceSoap.GetMInventoriesByManufacturerAsync(CozyComfortClient.MInventoryServiceReference.GetMInventoriesByManufacturerRequest request) {
            return base.Channel.GetMInventoriesByManufacturerAsync(request);
        }
        
        public System.Threading.Tasks.Task<CozyComfortClient.MInventoryServiceReference.GetMInventoriesByManufacturerResponse> GetMInventoriesByManufacturerAsync(int manufacturerId) {
            CozyComfortClient.MInventoryServiceReference.GetMInventoriesByManufacturerRequest inValue = new CozyComfortClient.MInventoryServiceReference.GetMInventoriesByManufacturerRequest();
            inValue.Body = new CozyComfortClient.MInventoryServiceReference.GetMInventoriesByManufacturerRequestBody();
            inValue.Body.manufacturerId = manufacturerId;
            return ((CozyComfortClient.MInventoryServiceReference.MInventoryServiceSoap)(this)).GetMInventoriesByManufacturerAsync(inValue);
        }
    }
}
