//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CozyComfortClient.UOrderServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderOperationResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class OrderOperationResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        private int OrderIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((this.OrderIdField.Equals(value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UOrderDetails", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class UOrderDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int OrderIdField;
        
        private int SellerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserContactField;
        
        private int BlanketIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BlanketModelField;
        
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        private System.DateTime OrderDateField;
        
        private System.Nullable<System.DateTime> ExpectedDeliveryDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((this.OrderIdField.Equals(value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SellerId {
            get {
                return this.SellerIdField;
            }
            set {
                if ((this.SellerIdField.Equals(value) != true)) {
                    this.SellerIdField = value;
                    this.RaisePropertyChanged("SellerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string UserContact {
            get {
                return this.UserContactField;
            }
            set {
                if ((object.ReferenceEquals(this.UserContactField, value) != true)) {
                    this.UserContactField = value;
                    this.RaisePropertyChanged("UserContact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int BlanketId {
            get {
                return this.BlanketIdField;
            }
            set {
                if ((this.BlanketIdField.Equals(value) != true)) {
                    this.BlanketIdField = value;
                    this.RaisePropertyChanged("BlanketId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string BlanketModel {
            get {
                return this.BlanketModelField;
            }
            set {
                if ((object.ReferenceEquals(this.BlanketModelField, value) != true)) {
                    this.BlanketModelField = value;
                    this.RaisePropertyChanged("BlanketModel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.DateTime OrderDate {
            get {
                return this.OrderDateField;
            }
            set {
                if ((this.OrderDateField.Equals(value) != true)) {
                    this.OrderDateField = value;
                    this.RaisePropertyChanged("OrderDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.Nullable<System.DateTime> ExpectedDeliveryDate {
            get {
                return this.ExpectedDeliveryDateField;
            }
            set {
                if ((this.ExpectedDeliveryDateField.Equals(value) != true)) {
                    this.ExpectedDeliveryDateField = value;
                    this.RaisePropertyChanged("ExpectedDeliveryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UOrderServiceReference.UOrderServiceSoap")]
    public interface UOrderServiceSoap {
        
        // CODEGEN: Generating message contract since element name userName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PlaceUOrder", ReplyAction="*")]
        CozyComfortClient.UOrderServiceReference.PlaceUOrderResponse PlaceUOrder(CozyComfortClient.UOrderServiceReference.PlaceUOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PlaceUOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<CozyComfortClient.UOrderServiceReference.PlaceUOrderResponse> PlaceUOrderAsync(CozyComfortClient.UOrderServiceReference.PlaceUOrderRequest request);
        
        // CODEGEN: Generating message contract since element name CancelUOrderResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CancelUOrder", ReplyAction="*")]
        CozyComfortClient.UOrderServiceReference.CancelUOrderResponse CancelUOrder(CozyComfortClient.UOrderServiceReference.CancelUOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CancelUOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<CozyComfortClient.UOrderServiceReference.CancelUOrderResponse> CancelUOrderAsync(CozyComfortClient.UOrderServiceReference.CancelUOrderRequest request);
        
        // CODEGEN: Generating message contract since element name newStatus from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateUOrderStatus", ReplyAction="*")]
        CozyComfortClient.UOrderServiceReference.UpdateUOrderStatusResponse UpdateUOrderStatus(CozyComfortClient.UOrderServiceReference.UpdateUOrderStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateUOrderStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<CozyComfortClient.UOrderServiceReference.UpdateUOrderStatusResponse> UpdateUOrderStatusAsync(CozyComfortClient.UOrderServiceReference.UpdateUOrderStatusRequest request);
        
        // CODEGEN: Generating message contract since element name statusFilter from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUOrdersBySeller", ReplyAction="*")]
        CozyComfortClient.UOrderServiceReference.GetUOrdersBySellerResponse GetUOrdersBySeller(CozyComfortClient.UOrderServiceReference.GetUOrdersBySellerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUOrdersBySeller", ReplyAction="*")]
        System.Threading.Tasks.Task<CozyComfortClient.UOrderServiceReference.GetUOrdersBySellerResponse> GetUOrdersBySellerAsync(CozyComfortClient.UOrderServiceReference.GetUOrdersBySellerRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PlaceUOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PlaceUOrder", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.UOrderServiceReference.PlaceUOrderRequestBody Body;
        
        public PlaceUOrderRequest() {
        }
        
        public PlaceUOrderRequest(CozyComfortClient.UOrderServiceReference.PlaceUOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PlaceUOrderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int sellerId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userContact;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int blanketId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int quantity;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.Nullable<System.DateTime> expectedDeliveryDate;
        
        public PlaceUOrderRequestBody() {
        }
        
        public PlaceUOrderRequestBody(int sellerId, string userName, string userContact, int blanketId, int quantity, System.Nullable<System.DateTime> expectedDeliveryDate) {
            this.sellerId = sellerId;
            this.userName = userName;
            this.userContact = userContact;
            this.blanketId = blanketId;
            this.quantity = quantity;
            this.expectedDeliveryDate = expectedDeliveryDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PlaceUOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PlaceUOrderResponse", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.UOrderServiceReference.PlaceUOrderResponseBody Body;
        
        public PlaceUOrderResponse() {
        }
        
        public PlaceUOrderResponse(CozyComfortClient.UOrderServiceReference.PlaceUOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PlaceUOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CozyComfortClient.UOrderServiceReference.OrderOperationResult PlaceUOrderResult;
        
        public PlaceUOrderResponseBody() {
        }
        
        public PlaceUOrderResponseBody(CozyComfortClient.UOrderServiceReference.OrderOperationResult PlaceUOrderResult) {
            this.PlaceUOrderResult = PlaceUOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelUOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelUOrder", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.UOrderServiceReference.CancelUOrderRequestBody Body;
        
        public CancelUOrderRequest() {
        }
        
        public CancelUOrderRequest(CozyComfortClient.UOrderServiceReference.CancelUOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CancelUOrderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int orderId;
        
        public CancelUOrderRequestBody() {
        }
        
        public CancelUOrderRequestBody(int orderId) {
            this.orderId = orderId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelUOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelUOrderResponse", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.UOrderServiceReference.CancelUOrderResponseBody Body;
        
        public CancelUOrderResponse() {
        }
        
        public CancelUOrderResponse(CozyComfortClient.UOrderServiceReference.CancelUOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CancelUOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CozyComfortClient.UOrderServiceReference.OrderOperationResult CancelUOrderResult;
        
        public CancelUOrderResponseBody() {
        }
        
        public CancelUOrderResponseBody(CozyComfortClient.UOrderServiceReference.OrderOperationResult CancelUOrderResult) {
            this.CancelUOrderResult = CancelUOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUOrderStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUOrderStatus", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.UOrderServiceReference.UpdateUOrderStatusRequestBody Body;
        
        public UpdateUOrderStatusRequest() {
        }
        
        public UpdateUOrderStatusRequest(CozyComfortClient.UOrderServiceReference.UpdateUOrderStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateUOrderStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string newStatus;
        
        public UpdateUOrderStatusRequestBody() {
        }
        
        public UpdateUOrderStatusRequestBody(int orderId, string newStatus) {
            this.orderId = orderId;
            this.newStatus = newStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUOrderStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUOrderStatusResponse", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.UOrderServiceReference.UpdateUOrderStatusResponseBody Body;
        
        public UpdateUOrderStatusResponse() {
        }
        
        public UpdateUOrderStatusResponse(CozyComfortClient.UOrderServiceReference.UpdateUOrderStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateUOrderStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CozyComfortClient.UOrderServiceReference.OrderOperationResult UpdateUOrderStatusResult;
        
        public UpdateUOrderStatusResponseBody() {
        }
        
        public UpdateUOrderStatusResponseBody(CozyComfortClient.UOrderServiceReference.OrderOperationResult UpdateUOrderStatusResult) {
            this.UpdateUOrderStatusResult = UpdateUOrderStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUOrdersBySellerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUOrdersBySeller", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.UOrderServiceReference.GetUOrdersBySellerRequestBody Body;
        
        public GetUOrdersBySellerRequest() {
        }
        
        public GetUOrdersBySellerRequest(CozyComfortClient.UOrderServiceReference.GetUOrdersBySellerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUOrdersBySellerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int sellerId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string statusFilter;
        
        public GetUOrdersBySellerRequestBody() {
        }
        
        public GetUOrdersBySellerRequestBody(int sellerId, string statusFilter) {
            this.sellerId = sellerId;
            this.statusFilter = statusFilter;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUOrdersBySellerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUOrdersBySellerResponse", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.UOrderServiceReference.GetUOrdersBySellerResponseBody Body;
        
        public GetUOrdersBySellerResponse() {
        }
        
        public GetUOrdersBySellerResponse(CozyComfortClient.UOrderServiceReference.GetUOrdersBySellerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUOrdersBySellerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CozyComfortClient.UOrderServiceReference.UOrderDetails[] GetUOrdersBySellerResult;
        
        public GetUOrdersBySellerResponseBody() {
        }
        
        public GetUOrdersBySellerResponseBody(CozyComfortClient.UOrderServiceReference.UOrderDetails[] GetUOrdersBySellerResult) {
            this.GetUOrdersBySellerResult = GetUOrdersBySellerResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UOrderServiceSoapChannel : CozyComfortClient.UOrderServiceReference.UOrderServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UOrderServiceSoapClient : System.ServiceModel.ClientBase<CozyComfortClient.UOrderServiceReference.UOrderServiceSoap>, CozyComfortClient.UOrderServiceReference.UOrderServiceSoap {
        
        public UOrderServiceSoapClient() {
        }
        
        public UOrderServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UOrderServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UOrderServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UOrderServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CozyComfortClient.UOrderServiceReference.PlaceUOrderResponse CozyComfortClient.UOrderServiceReference.UOrderServiceSoap.PlaceUOrder(CozyComfortClient.UOrderServiceReference.PlaceUOrderRequest request) {
            return base.Channel.PlaceUOrder(request);
        }
        
        public CozyComfortClient.UOrderServiceReference.OrderOperationResult PlaceUOrder(int sellerId, string userName, string userContact, int blanketId, int quantity, System.Nullable<System.DateTime> expectedDeliveryDate) {
            CozyComfortClient.UOrderServiceReference.PlaceUOrderRequest inValue = new CozyComfortClient.UOrderServiceReference.PlaceUOrderRequest();
            inValue.Body = new CozyComfortClient.UOrderServiceReference.PlaceUOrderRequestBody();
            inValue.Body.sellerId = sellerId;
            inValue.Body.userName = userName;
            inValue.Body.userContact = userContact;
            inValue.Body.blanketId = blanketId;
            inValue.Body.quantity = quantity;
            inValue.Body.expectedDeliveryDate = expectedDeliveryDate;
            CozyComfortClient.UOrderServiceReference.PlaceUOrderResponse retVal = ((CozyComfortClient.UOrderServiceReference.UOrderServiceSoap)(this)).PlaceUOrder(inValue);
            return retVal.Body.PlaceUOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CozyComfortClient.UOrderServiceReference.PlaceUOrderResponse> CozyComfortClient.UOrderServiceReference.UOrderServiceSoap.PlaceUOrderAsync(CozyComfortClient.UOrderServiceReference.PlaceUOrderRequest request) {
            return base.Channel.PlaceUOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<CozyComfortClient.UOrderServiceReference.PlaceUOrderResponse> PlaceUOrderAsync(int sellerId, string userName, string userContact, int blanketId, int quantity, System.Nullable<System.DateTime> expectedDeliveryDate) {
            CozyComfortClient.UOrderServiceReference.PlaceUOrderRequest inValue = new CozyComfortClient.UOrderServiceReference.PlaceUOrderRequest();
            inValue.Body = new CozyComfortClient.UOrderServiceReference.PlaceUOrderRequestBody();
            inValue.Body.sellerId = sellerId;
            inValue.Body.userName = userName;
            inValue.Body.userContact = userContact;
            inValue.Body.blanketId = blanketId;
            inValue.Body.quantity = quantity;
            inValue.Body.expectedDeliveryDate = expectedDeliveryDate;
            return ((CozyComfortClient.UOrderServiceReference.UOrderServiceSoap)(this)).PlaceUOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CozyComfortClient.UOrderServiceReference.CancelUOrderResponse CozyComfortClient.UOrderServiceReference.UOrderServiceSoap.CancelUOrder(CozyComfortClient.UOrderServiceReference.CancelUOrderRequest request) {
            return base.Channel.CancelUOrder(request);
        }
        
        public CozyComfortClient.UOrderServiceReference.OrderOperationResult CancelUOrder(int orderId) {
            CozyComfortClient.UOrderServiceReference.CancelUOrderRequest inValue = new CozyComfortClient.UOrderServiceReference.CancelUOrderRequest();
            inValue.Body = new CozyComfortClient.UOrderServiceReference.CancelUOrderRequestBody();
            inValue.Body.orderId = orderId;
            CozyComfortClient.UOrderServiceReference.CancelUOrderResponse retVal = ((CozyComfortClient.UOrderServiceReference.UOrderServiceSoap)(this)).CancelUOrder(inValue);
            return retVal.Body.CancelUOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CozyComfortClient.UOrderServiceReference.CancelUOrderResponse> CozyComfortClient.UOrderServiceReference.UOrderServiceSoap.CancelUOrderAsync(CozyComfortClient.UOrderServiceReference.CancelUOrderRequest request) {
            return base.Channel.CancelUOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<CozyComfortClient.UOrderServiceReference.CancelUOrderResponse> CancelUOrderAsync(int orderId) {
            CozyComfortClient.UOrderServiceReference.CancelUOrderRequest inValue = new CozyComfortClient.UOrderServiceReference.CancelUOrderRequest();
            inValue.Body = new CozyComfortClient.UOrderServiceReference.CancelUOrderRequestBody();
            inValue.Body.orderId = orderId;
            return ((CozyComfortClient.UOrderServiceReference.UOrderServiceSoap)(this)).CancelUOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CozyComfortClient.UOrderServiceReference.UpdateUOrderStatusResponse CozyComfortClient.UOrderServiceReference.UOrderServiceSoap.UpdateUOrderStatus(CozyComfortClient.UOrderServiceReference.UpdateUOrderStatusRequest request) {
            return base.Channel.UpdateUOrderStatus(request);
        }
        
        public CozyComfortClient.UOrderServiceReference.OrderOperationResult UpdateUOrderStatus(int orderId, string newStatus) {
            CozyComfortClient.UOrderServiceReference.UpdateUOrderStatusRequest inValue = new CozyComfortClient.UOrderServiceReference.UpdateUOrderStatusRequest();
            inValue.Body = new CozyComfortClient.UOrderServiceReference.UpdateUOrderStatusRequestBody();
            inValue.Body.orderId = orderId;
            inValue.Body.newStatus = newStatus;
            CozyComfortClient.UOrderServiceReference.UpdateUOrderStatusResponse retVal = ((CozyComfortClient.UOrderServiceReference.UOrderServiceSoap)(this)).UpdateUOrderStatus(inValue);
            return retVal.Body.UpdateUOrderStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CozyComfortClient.UOrderServiceReference.UpdateUOrderStatusResponse> CozyComfortClient.UOrderServiceReference.UOrderServiceSoap.UpdateUOrderStatusAsync(CozyComfortClient.UOrderServiceReference.UpdateUOrderStatusRequest request) {
            return base.Channel.UpdateUOrderStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<CozyComfortClient.UOrderServiceReference.UpdateUOrderStatusResponse> UpdateUOrderStatusAsync(int orderId, string newStatus) {
            CozyComfortClient.UOrderServiceReference.UpdateUOrderStatusRequest inValue = new CozyComfortClient.UOrderServiceReference.UpdateUOrderStatusRequest();
            inValue.Body = new CozyComfortClient.UOrderServiceReference.UpdateUOrderStatusRequestBody();
            inValue.Body.orderId = orderId;
            inValue.Body.newStatus = newStatus;
            return ((CozyComfortClient.UOrderServiceReference.UOrderServiceSoap)(this)).UpdateUOrderStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CozyComfortClient.UOrderServiceReference.GetUOrdersBySellerResponse CozyComfortClient.UOrderServiceReference.UOrderServiceSoap.GetUOrdersBySeller(CozyComfortClient.UOrderServiceReference.GetUOrdersBySellerRequest request) {
            return base.Channel.GetUOrdersBySeller(request);
        }
        
        public CozyComfortClient.UOrderServiceReference.UOrderDetails[] GetUOrdersBySeller(int sellerId, string statusFilter) {
            CozyComfortClient.UOrderServiceReference.GetUOrdersBySellerRequest inValue = new CozyComfortClient.UOrderServiceReference.GetUOrdersBySellerRequest();
            inValue.Body = new CozyComfortClient.UOrderServiceReference.GetUOrdersBySellerRequestBody();
            inValue.Body.sellerId = sellerId;
            inValue.Body.statusFilter = statusFilter;
            CozyComfortClient.UOrderServiceReference.GetUOrdersBySellerResponse retVal = ((CozyComfortClient.UOrderServiceReference.UOrderServiceSoap)(this)).GetUOrdersBySeller(inValue);
            return retVal.Body.GetUOrdersBySellerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CozyComfortClient.UOrderServiceReference.GetUOrdersBySellerResponse> CozyComfortClient.UOrderServiceReference.UOrderServiceSoap.GetUOrdersBySellerAsync(CozyComfortClient.UOrderServiceReference.GetUOrdersBySellerRequest request) {
            return base.Channel.GetUOrdersBySellerAsync(request);
        }
        
        public System.Threading.Tasks.Task<CozyComfortClient.UOrderServiceReference.GetUOrdersBySellerResponse> GetUOrdersBySellerAsync(int sellerId, string statusFilter) {
            CozyComfortClient.UOrderServiceReference.GetUOrdersBySellerRequest inValue = new CozyComfortClient.UOrderServiceReference.GetUOrdersBySellerRequest();
            inValue.Body = new CozyComfortClient.UOrderServiceReference.GetUOrdersBySellerRequestBody();
            inValue.Body.sellerId = sellerId;
            inValue.Body.statusFilter = statusFilter;
            return ((CozyComfortClient.UOrderServiceReference.UOrderServiceSoap)(this)).GetUOrdersBySellerAsync(inValue);
        }
    }
}
