//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CozyComfortClient.DOrderServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderOperationResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class OrderOperationResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        private int OrderIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((this.OrderIdField.Equals(value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DOrderDetails", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DOrderDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int OrderIdField;
        
        private int DistributorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistributorNameField;
        
        private int ManufacturerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ManufacturerNameField;
        
        private int BlanketIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BlanketModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BlanketMaterialField;
        
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        private System.DateTime OrderDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((this.OrderIdField.Equals(value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int DistributorId {
            get {
                return this.DistributorIdField;
            }
            set {
                if ((this.DistributorIdField.Equals(value) != true)) {
                    this.DistributorIdField = value;
                    this.RaisePropertyChanged("DistributorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DistributorName {
            get {
                return this.DistributorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DistributorNameField, value) != true)) {
                    this.DistributorNameField = value;
                    this.RaisePropertyChanged("DistributorName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int ManufacturerId {
            get {
                return this.ManufacturerIdField;
            }
            set {
                if ((this.ManufacturerIdField.Equals(value) != true)) {
                    this.ManufacturerIdField = value;
                    this.RaisePropertyChanged("ManufacturerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ManufacturerName {
            get {
                return this.ManufacturerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ManufacturerNameField, value) != true)) {
                    this.ManufacturerNameField = value;
                    this.RaisePropertyChanged("ManufacturerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int BlanketId {
            get {
                return this.BlanketIdField;
            }
            set {
                if ((this.BlanketIdField.Equals(value) != true)) {
                    this.BlanketIdField = value;
                    this.RaisePropertyChanged("BlanketId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string BlanketModel {
            get {
                return this.BlanketModelField;
            }
            set {
                if ((object.ReferenceEquals(this.BlanketModelField, value) != true)) {
                    this.BlanketModelField = value;
                    this.RaisePropertyChanged("BlanketModel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string BlanketMaterial {
            get {
                return this.BlanketMaterialField;
            }
            set {
                if ((object.ReferenceEquals(this.BlanketMaterialField, value) != true)) {
                    this.BlanketMaterialField = value;
                    this.RaisePropertyChanged("BlanketMaterial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.DateTime OrderDate {
            get {
                return this.OrderDateField;
            }
            set {
                if ((this.OrderDateField.Equals(value) != true)) {
                    this.OrderDateField = value;
                    this.RaisePropertyChanged("OrderDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ManufacturerBlanket", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ManufacturerBlanket : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ManufacturerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ManufacturerNameField;
        
        private int AvailableQuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ManufacturerId {
            get {
                return this.ManufacturerIdField;
            }
            set {
                if ((this.ManufacturerIdField.Equals(value) != true)) {
                    this.ManufacturerIdField = value;
                    this.RaisePropertyChanged("ManufacturerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ManufacturerName {
            get {
                return this.ManufacturerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ManufacturerNameField, value) != true)) {
                    this.ManufacturerNameField = value;
                    this.RaisePropertyChanged("ManufacturerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int AvailableQuantity {
            get {
                return this.AvailableQuantityField;
            }
            set {
                if ((this.AvailableQuantityField.Equals(value) != true)) {
                    this.AvailableQuantityField = value;
                    this.RaisePropertyChanged("AvailableQuantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DOrderServiceReference.DOrderServiceSoap")]
    public interface DOrderServiceSoap {
        
        // CODEGEN: Generating message contract since element name PlaceDistributorOrderResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PlaceDistributorOrder", ReplyAction="*")]
        CozyComfortClient.DOrderServiceReference.PlaceDistributorOrderResponse PlaceDistributorOrder(CozyComfortClient.DOrderServiceReference.PlaceDistributorOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PlaceDistributorOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<CozyComfortClient.DOrderServiceReference.PlaceDistributorOrderResponse> PlaceDistributorOrderAsync(CozyComfortClient.DOrderServiceReference.PlaceDistributorOrderRequest request);
        
        // CODEGEN: Generating message contract since element name newStatus from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateDistributorOrderStatus", ReplyAction="*")]
        CozyComfortClient.DOrderServiceReference.UpdateDistributorOrderStatusResponse UpdateDistributorOrderStatus(CozyComfortClient.DOrderServiceReference.UpdateDistributorOrderStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateDistributorOrderStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<CozyComfortClient.DOrderServiceReference.UpdateDistributorOrderStatusResponse> UpdateDistributorOrderStatusAsync(CozyComfortClient.DOrderServiceReference.UpdateDistributorOrderStatusRequest request);
        
        // CODEGEN: Generating message contract since element name CancelDistributorOrderResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CancelDistributorOrder", ReplyAction="*")]
        CozyComfortClient.DOrderServiceReference.CancelDistributorOrderResponse CancelDistributorOrder(CozyComfortClient.DOrderServiceReference.CancelDistributorOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CancelDistributorOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<CozyComfortClient.DOrderServiceReference.CancelDistributorOrderResponse> CancelDistributorOrderAsync(CozyComfortClient.DOrderServiceReference.CancelDistributorOrderRequest request);
        
        // CODEGEN: Generating message contract since element name GetDistributorOrderDetailsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDistributorOrderDetails", ReplyAction="*")]
        CozyComfortClient.DOrderServiceReference.GetDistributorOrderDetailsResponse GetDistributorOrderDetails(CozyComfortClient.DOrderServiceReference.GetDistributorOrderDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDistributorOrderDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<CozyComfortClient.DOrderServiceReference.GetDistributorOrderDetailsResponse> GetDistributorOrderDetailsAsync(CozyComfortClient.DOrderServiceReference.GetDistributorOrderDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name statusFilter from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDistributorOrdersByManufacturer", ReplyAction="*")]
        CozyComfortClient.DOrderServiceReference.GetDistributorOrdersByManufacturerResponse GetDistributorOrdersByManufacturer(CozyComfortClient.DOrderServiceReference.GetDistributorOrdersByManufacturerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDistributorOrdersByManufacturer", ReplyAction="*")]
        System.Threading.Tasks.Task<CozyComfortClient.DOrderServiceReference.GetDistributorOrdersByManufacturerResponse> GetDistributorOrdersByManufacturerAsync(CozyComfortClient.DOrderServiceReference.GetDistributorOrdersByManufacturerRequest request);
        
        // CODEGEN: Generating message contract since element name statusFilter from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDistributorOrdersByDistributor", ReplyAction="*")]
        CozyComfortClient.DOrderServiceReference.GetDistributorOrdersByDistributorResponse GetDistributorOrdersByDistributor(CozyComfortClient.DOrderServiceReference.GetDistributorOrdersByDistributorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDistributorOrdersByDistributor", ReplyAction="*")]
        System.Threading.Tasks.Task<CozyComfortClient.DOrderServiceReference.GetDistributorOrdersByDistributorResponse> GetDistributorOrdersByDistributorAsync(CozyComfortClient.DOrderServiceReference.GetDistributorOrdersByDistributorRequest request);
        
        // CODEGEN: Generating message contract since element name GetManufacturersForBlanketResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetManufacturersForBlanket", ReplyAction="*")]
        CozyComfortClient.DOrderServiceReference.GetManufacturersForBlanketResponse GetManufacturersForBlanket(CozyComfortClient.DOrderServiceReference.GetManufacturersForBlanketRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetManufacturersForBlanket", ReplyAction="*")]
        System.Threading.Tasks.Task<CozyComfortClient.DOrderServiceReference.GetManufacturersForBlanketResponse> GetManufacturersForBlanketAsync(CozyComfortClient.DOrderServiceReference.GetManufacturersForBlanketRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PlaceDistributorOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PlaceDistributorOrder", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.DOrderServiceReference.PlaceDistributorOrderRequestBody Body;
        
        public PlaceDistributorOrderRequest() {
        }
        
        public PlaceDistributorOrderRequest(CozyComfortClient.DOrderServiceReference.PlaceDistributorOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PlaceDistributorOrderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int distributorId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int manufacturerId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int blanketId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int quantity;
        
        public PlaceDistributorOrderRequestBody() {
        }
        
        public PlaceDistributorOrderRequestBody(int distributorId, int manufacturerId, int blanketId, int quantity) {
            this.distributorId = distributorId;
            this.manufacturerId = manufacturerId;
            this.blanketId = blanketId;
            this.quantity = quantity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PlaceDistributorOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PlaceDistributorOrderResponse", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.DOrderServiceReference.PlaceDistributorOrderResponseBody Body;
        
        public PlaceDistributorOrderResponse() {
        }
        
        public PlaceDistributorOrderResponse(CozyComfortClient.DOrderServiceReference.PlaceDistributorOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PlaceDistributorOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CozyComfortClient.DOrderServiceReference.OrderOperationResult PlaceDistributorOrderResult;
        
        public PlaceDistributorOrderResponseBody() {
        }
        
        public PlaceDistributorOrderResponseBody(CozyComfortClient.DOrderServiceReference.OrderOperationResult PlaceDistributorOrderResult) {
            this.PlaceDistributorOrderResult = PlaceDistributorOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateDistributorOrderStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateDistributorOrderStatus", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.DOrderServiceReference.UpdateDistributorOrderStatusRequestBody Body;
        
        public UpdateDistributorOrderStatusRequest() {
        }
        
        public UpdateDistributorOrderStatusRequest(CozyComfortClient.DOrderServiceReference.UpdateDistributorOrderStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateDistributorOrderStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string newStatus;
        
        public UpdateDistributorOrderStatusRequestBody() {
        }
        
        public UpdateDistributorOrderStatusRequestBody(int orderId, string newStatus) {
            this.orderId = orderId;
            this.newStatus = newStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateDistributorOrderStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateDistributorOrderStatusResponse", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.DOrderServiceReference.UpdateDistributorOrderStatusResponseBody Body;
        
        public UpdateDistributorOrderStatusResponse() {
        }
        
        public UpdateDistributorOrderStatusResponse(CozyComfortClient.DOrderServiceReference.UpdateDistributorOrderStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateDistributorOrderStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CozyComfortClient.DOrderServiceReference.OrderOperationResult UpdateDistributorOrderStatusResult;
        
        public UpdateDistributorOrderStatusResponseBody() {
        }
        
        public UpdateDistributorOrderStatusResponseBody(CozyComfortClient.DOrderServiceReference.OrderOperationResult UpdateDistributorOrderStatusResult) {
            this.UpdateDistributorOrderStatusResult = UpdateDistributorOrderStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelDistributorOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelDistributorOrder", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.DOrderServiceReference.CancelDistributorOrderRequestBody Body;
        
        public CancelDistributorOrderRequest() {
        }
        
        public CancelDistributorOrderRequest(CozyComfortClient.DOrderServiceReference.CancelDistributorOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CancelDistributorOrderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int orderId;
        
        public CancelDistributorOrderRequestBody() {
        }
        
        public CancelDistributorOrderRequestBody(int orderId) {
            this.orderId = orderId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelDistributorOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelDistributorOrderResponse", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.DOrderServiceReference.CancelDistributorOrderResponseBody Body;
        
        public CancelDistributorOrderResponse() {
        }
        
        public CancelDistributorOrderResponse(CozyComfortClient.DOrderServiceReference.CancelDistributorOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CancelDistributorOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CozyComfortClient.DOrderServiceReference.OrderOperationResult CancelDistributorOrderResult;
        
        public CancelDistributorOrderResponseBody() {
        }
        
        public CancelDistributorOrderResponseBody(CozyComfortClient.DOrderServiceReference.OrderOperationResult CancelDistributorOrderResult) {
            this.CancelDistributorOrderResult = CancelDistributorOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDistributorOrderDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDistributorOrderDetails", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.DOrderServiceReference.GetDistributorOrderDetailsRequestBody Body;
        
        public GetDistributorOrderDetailsRequest() {
        }
        
        public GetDistributorOrderDetailsRequest(CozyComfortClient.DOrderServiceReference.GetDistributorOrderDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDistributorOrderDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int orderId;
        
        public GetDistributorOrderDetailsRequestBody() {
        }
        
        public GetDistributorOrderDetailsRequestBody(int orderId) {
            this.orderId = orderId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDistributorOrderDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDistributorOrderDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.DOrderServiceReference.GetDistributorOrderDetailsResponseBody Body;
        
        public GetDistributorOrderDetailsResponse() {
        }
        
        public GetDistributorOrderDetailsResponse(CozyComfortClient.DOrderServiceReference.GetDistributorOrderDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDistributorOrderDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CozyComfortClient.DOrderServiceReference.DOrderDetails GetDistributorOrderDetailsResult;
        
        public GetDistributorOrderDetailsResponseBody() {
        }
        
        public GetDistributorOrderDetailsResponseBody(CozyComfortClient.DOrderServiceReference.DOrderDetails GetDistributorOrderDetailsResult) {
            this.GetDistributorOrderDetailsResult = GetDistributorOrderDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDistributorOrdersByManufacturerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDistributorOrdersByManufacturer", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.DOrderServiceReference.GetDistributorOrdersByManufacturerRequestBody Body;
        
        public GetDistributorOrdersByManufacturerRequest() {
        }
        
        public GetDistributorOrdersByManufacturerRequest(CozyComfortClient.DOrderServiceReference.GetDistributorOrdersByManufacturerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDistributorOrdersByManufacturerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int manufacturerId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string statusFilter;
        
        public GetDistributorOrdersByManufacturerRequestBody() {
        }
        
        public GetDistributorOrdersByManufacturerRequestBody(int manufacturerId, string statusFilter) {
            this.manufacturerId = manufacturerId;
            this.statusFilter = statusFilter;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDistributorOrdersByManufacturerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDistributorOrdersByManufacturerResponse", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.DOrderServiceReference.GetDistributorOrdersByManufacturerResponseBody Body;
        
        public GetDistributorOrdersByManufacturerResponse() {
        }
        
        public GetDistributorOrdersByManufacturerResponse(CozyComfortClient.DOrderServiceReference.GetDistributorOrdersByManufacturerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDistributorOrdersByManufacturerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CozyComfortClient.DOrderServiceReference.DOrderDetails[] GetDistributorOrdersByManufacturerResult;
        
        public GetDistributorOrdersByManufacturerResponseBody() {
        }
        
        public GetDistributorOrdersByManufacturerResponseBody(CozyComfortClient.DOrderServiceReference.DOrderDetails[] GetDistributorOrdersByManufacturerResult) {
            this.GetDistributorOrdersByManufacturerResult = GetDistributorOrdersByManufacturerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDistributorOrdersByDistributorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDistributorOrdersByDistributor", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.DOrderServiceReference.GetDistributorOrdersByDistributorRequestBody Body;
        
        public GetDistributorOrdersByDistributorRequest() {
        }
        
        public GetDistributorOrdersByDistributorRequest(CozyComfortClient.DOrderServiceReference.GetDistributorOrdersByDistributorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDistributorOrdersByDistributorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int distributorId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string statusFilter;
        
        public GetDistributorOrdersByDistributorRequestBody() {
        }
        
        public GetDistributorOrdersByDistributorRequestBody(int distributorId, string statusFilter) {
            this.distributorId = distributorId;
            this.statusFilter = statusFilter;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDistributorOrdersByDistributorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDistributorOrdersByDistributorResponse", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.DOrderServiceReference.GetDistributorOrdersByDistributorResponseBody Body;
        
        public GetDistributorOrdersByDistributorResponse() {
        }
        
        public GetDistributorOrdersByDistributorResponse(CozyComfortClient.DOrderServiceReference.GetDistributorOrdersByDistributorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDistributorOrdersByDistributorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CozyComfortClient.DOrderServiceReference.DOrderDetails[] GetDistributorOrdersByDistributorResult;
        
        public GetDistributorOrdersByDistributorResponseBody() {
        }
        
        public GetDistributorOrdersByDistributorResponseBody(CozyComfortClient.DOrderServiceReference.DOrderDetails[] GetDistributorOrdersByDistributorResult) {
            this.GetDistributorOrdersByDistributorResult = GetDistributorOrdersByDistributorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetManufacturersForBlanketRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetManufacturersForBlanket", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.DOrderServiceReference.GetManufacturersForBlanketRequestBody Body;
        
        public GetManufacturersForBlanketRequest() {
        }
        
        public GetManufacturersForBlanketRequest(CozyComfortClient.DOrderServiceReference.GetManufacturersForBlanketRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetManufacturersForBlanketRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int blanketId;
        
        public GetManufacturersForBlanketRequestBody() {
        }
        
        public GetManufacturersForBlanketRequestBody(int blanketId) {
            this.blanketId = blanketId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetManufacturersForBlanketResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetManufacturersForBlanketResponse", Namespace="http://tempuri.org/", Order=0)]
        public CozyComfortClient.DOrderServiceReference.GetManufacturersForBlanketResponseBody Body;
        
        public GetManufacturersForBlanketResponse() {
        }
        
        public GetManufacturersForBlanketResponse(CozyComfortClient.DOrderServiceReference.GetManufacturersForBlanketResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetManufacturersForBlanketResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CozyComfortClient.DOrderServiceReference.ManufacturerBlanket[] GetManufacturersForBlanketResult;
        
        public GetManufacturersForBlanketResponseBody() {
        }
        
        public GetManufacturersForBlanketResponseBody(CozyComfortClient.DOrderServiceReference.ManufacturerBlanket[] GetManufacturersForBlanketResult) {
            this.GetManufacturersForBlanketResult = GetManufacturersForBlanketResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DOrderServiceSoapChannel : CozyComfortClient.DOrderServiceReference.DOrderServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DOrderServiceSoapClient : System.ServiceModel.ClientBase<CozyComfortClient.DOrderServiceReference.DOrderServiceSoap>, CozyComfortClient.DOrderServiceReference.DOrderServiceSoap {
        
        public DOrderServiceSoapClient() {
        }
        
        public DOrderServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DOrderServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DOrderServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DOrderServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CozyComfortClient.DOrderServiceReference.PlaceDistributorOrderResponse CozyComfortClient.DOrderServiceReference.DOrderServiceSoap.PlaceDistributorOrder(CozyComfortClient.DOrderServiceReference.PlaceDistributorOrderRequest request) {
            return base.Channel.PlaceDistributorOrder(request);
        }
        
        public CozyComfortClient.DOrderServiceReference.OrderOperationResult PlaceDistributorOrder(int distributorId, int manufacturerId, int blanketId, int quantity) {
            CozyComfortClient.DOrderServiceReference.PlaceDistributorOrderRequest inValue = new CozyComfortClient.DOrderServiceReference.PlaceDistributorOrderRequest();
            inValue.Body = new CozyComfortClient.DOrderServiceReference.PlaceDistributorOrderRequestBody();
            inValue.Body.distributorId = distributorId;
            inValue.Body.manufacturerId = manufacturerId;
            inValue.Body.blanketId = blanketId;
            inValue.Body.quantity = quantity;
            CozyComfortClient.DOrderServiceReference.PlaceDistributorOrderResponse retVal = ((CozyComfortClient.DOrderServiceReference.DOrderServiceSoap)(this)).PlaceDistributorOrder(inValue);
            return retVal.Body.PlaceDistributorOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CozyComfortClient.DOrderServiceReference.PlaceDistributorOrderResponse> CozyComfortClient.DOrderServiceReference.DOrderServiceSoap.PlaceDistributorOrderAsync(CozyComfortClient.DOrderServiceReference.PlaceDistributorOrderRequest request) {
            return base.Channel.PlaceDistributorOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<CozyComfortClient.DOrderServiceReference.PlaceDistributorOrderResponse> PlaceDistributorOrderAsync(int distributorId, int manufacturerId, int blanketId, int quantity) {
            CozyComfortClient.DOrderServiceReference.PlaceDistributorOrderRequest inValue = new CozyComfortClient.DOrderServiceReference.PlaceDistributorOrderRequest();
            inValue.Body = new CozyComfortClient.DOrderServiceReference.PlaceDistributorOrderRequestBody();
            inValue.Body.distributorId = distributorId;
            inValue.Body.manufacturerId = manufacturerId;
            inValue.Body.blanketId = blanketId;
            inValue.Body.quantity = quantity;
            return ((CozyComfortClient.DOrderServiceReference.DOrderServiceSoap)(this)).PlaceDistributorOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CozyComfortClient.DOrderServiceReference.UpdateDistributorOrderStatusResponse CozyComfortClient.DOrderServiceReference.DOrderServiceSoap.UpdateDistributorOrderStatus(CozyComfortClient.DOrderServiceReference.UpdateDistributorOrderStatusRequest request) {
            return base.Channel.UpdateDistributorOrderStatus(request);
        }
        
        public CozyComfortClient.DOrderServiceReference.OrderOperationResult UpdateDistributorOrderStatus(int orderId, string newStatus) {
            CozyComfortClient.DOrderServiceReference.UpdateDistributorOrderStatusRequest inValue = new CozyComfortClient.DOrderServiceReference.UpdateDistributorOrderStatusRequest();
            inValue.Body = new CozyComfortClient.DOrderServiceReference.UpdateDistributorOrderStatusRequestBody();
            inValue.Body.orderId = orderId;
            inValue.Body.newStatus = newStatus;
            CozyComfortClient.DOrderServiceReference.UpdateDistributorOrderStatusResponse retVal = ((CozyComfortClient.DOrderServiceReference.DOrderServiceSoap)(this)).UpdateDistributorOrderStatus(inValue);
            return retVal.Body.UpdateDistributorOrderStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CozyComfortClient.DOrderServiceReference.UpdateDistributorOrderStatusResponse> CozyComfortClient.DOrderServiceReference.DOrderServiceSoap.UpdateDistributorOrderStatusAsync(CozyComfortClient.DOrderServiceReference.UpdateDistributorOrderStatusRequest request) {
            return base.Channel.UpdateDistributorOrderStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<CozyComfortClient.DOrderServiceReference.UpdateDistributorOrderStatusResponse> UpdateDistributorOrderStatusAsync(int orderId, string newStatus) {
            CozyComfortClient.DOrderServiceReference.UpdateDistributorOrderStatusRequest inValue = new CozyComfortClient.DOrderServiceReference.UpdateDistributorOrderStatusRequest();
            inValue.Body = new CozyComfortClient.DOrderServiceReference.UpdateDistributorOrderStatusRequestBody();
            inValue.Body.orderId = orderId;
            inValue.Body.newStatus = newStatus;
            return ((CozyComfortClient.DOrderServiceReference.DOrderServiceSoap)(this)).UpdateDistributorOrderStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CozyComfortClient.DOrderServiceReference.CancelDistributorOrderResponse CozyComfortClient.DOrderServiceReference.DOrderServiceSoap.CancelDistributorOrder(CozyComfortClient.DOrderServiceReference.CancelDistributorOrderRequest request) {
            return base.Channel.CancelDistributorOrder(request);
        }
        
        public CozyComfortClient.DOrderServiceReference.OrderOperationResult CancelDistributorOrder(int orderId) {
            CozyComfortClient.DOrderServiceReference.CancelDistributorOrderRequest inValue = new CozyComfortClient.DOrderServiceReference.CancelDistributorOrderRequest();
            inValue.Body = new CozyComfortClient.DOrderServiceReference.CancelDistributorOrderRequestBody();
            inValue.Body.orderId = orderId;
            CozyComfortClient.DOrderServiceReference.CancelDistributorOrderResponse retVal = ((CozyComfortClient.DOrderServiceReference.DOrderServiceSoap)(this)).CancelDistributorOrder(inValue);
            return retVal.Body.CancelDistributorOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CozyComfortClient.DOrderServiceReference.CancelDistributorOrderResponse> CozyComfortClient.DOrderServiceReference.DOrderServiceSoap.CancelDistributorOrderAsync(CozyComfortClient.DOrderServiceReference.CancelDistributorOrderRequest request) {
            return base.Channel.CancelDistributorOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<CozyComfortClient.DOrderServiceReference.CancelDistributorOrderResponse> CancelDistributorOrderAsync(int orderId) {
            CozyComfortClient.DOrderServiceReference.CancelDistributorOrderRequest inValue = new CozyComfortClient.DOrderServiceReference.CancelDistributorOrderRequest();
            inValue.Body = new CozyComfortClient.DOrderServiceReference.CancelDistributorOrderRequestBody();
            inValue.Body.orderId = orderId;
            return ((CozyComfortClient.DOrderServiceReference.DOrderServiceSoap)(this)).CancelDistributorOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CozyComfortClient.DOrderServiceReference.GetDistributorOrderDetailsResponse CozyComfortClient.DOrderServiceReference.DOrderServiceSoap.GetDistributorOrderDetails(CozyComfortClient.DOrderServiceReference.GetDistributorOrderDetailsRequest request) {
            return base.Channel.GetDistributorOrderDetails(request);
        }
        
        public CozyComfortClient.DOrderServiceReference.DOrderDetails GetDistributorOrderDetails(int orderId) {
            CozyComfortClient.DOrderServiceReference.GetDistributorOrderDetailsRequest inValue = new CozyComfortClient.DOrderServiceReference.GetDistributorOrderDetailsRequest();
            inValue.Body = new CozyComfortClient.DOrderServiceReference.GetDistributorOrderDetailsRequestBody();
            inValue.Body.orderId = orderId;
            CozyComfortClient.DOrderServiceReference.GetDistributorOrderDetailsResponse retVal = ((CozyComfortClient.DOrderServiceReference.DOrderServiceSoap)(this)).GetDistributorOrderDetails(inValue);
            return retVal.Body.GetDistributorOrderDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CozyComfortClient.DOrderServiceReference.GetDistributorOrderDetailsResponse> CozyComfortClient.DOrderServiceReference.DOrderServiceSoap.GetDistributorOrderDetailsAsync(CozyComfortClient.DOrderServiceReference.GetDistributorOrderDetailsRequest request) {
            return base.Channel.GetDistributorOrderDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<CozyComfortClient.DOrderServiceReference.GetDistributorOrderDetailsResponse> GetDistributorOrderDetailsAsync(int orderId) {
            CozyComfortClient.DOrderServiceReference.GetDistributorOrderDetailsRequest inValue = new CozyComfortClient.DOrderServiceReference.GetDistributorOrderDetailsRequest();
            inValue.Body = new CozyComfortClient.DOrderServiceReference.GetDistributorOrderDetailsRequestBody();
            inValue.Body.orderId = orderId;
            return ((CozyComfortClient.DOrderServiceReference.DOrderServiceSoap)(this)).GetDistributorOrderDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CozyComfortClient.DOrderServiceReference.GetDistributorOrdersByManufacturerResponse CozyComfortClient.DOrderServiceReference.DOrderServiceSoap.GetDistributorOrdersByManufacturer(CozyComfortClient.DOrderServiceReference.GetDistributorOrdersByManufacturerRequest request) {
            return base.Channel.GetDistributorOrdersByManufacturer(request);
        }
        
        public CozyComfortClient.DOrderServiceReference.DOrderDetails[] GetDistributorOrdersByManufacturer(int manufacturerId, string statusFilter) {
            CozyComfortClient.DOrderServiceReference.GetDistributorOrdersByManufacturerRequest inValue = new CozyComfortClient.DOrderServiceReference.GetDistributorOrdersByManufacturerRequest();
            inValue.Body = new CozyComfortClient.DOrderServiceReference.GetDistributorOrdersByManufacturerRequestBody();
            inValue.Body.manufacturerId = manufacturerId;
            inValue.Body.statusFilter = statusFilter;
            CozyComfortClient.DOrderServiceReference.GetDistributorOrdersByManufacturerResponse retVal = ((CozyComfortClient.DOrderServiceReference.DOrderServiceSoap)(this)).GetDistributorOrdersByManufacturer(inValue);
            return retVal.Body.GetDistributorOrdersByManufacturerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CozyComfortClient.DOrderServiceReference.GetDistributorOrdersByManufacturerResponse> CozyComfortClient.DOrderServiceReference.DOrderServiceSoap.GetDistributorOrdersByManufacturerAsync(CozyComfortClient.DOrderServiceReference.GetDistributorOrdersByManufacturerRequest request) {
            return base.Channel.GetDistributorOrdersByManufacturerAsync(request);
        }
        
        public System.Threading.Tasks.Task<CozyComfortClient.DOrderServiceReference.GetDistributorOrdersByManufacturerResponse> GetDistributorOrdersByManufacturerAsync(int manufacturerId, string statusFilter) {
            CozyComfortClient.DOrderServiceReference.GetDistributorOrdersByManufacturerRequest inValue = new CozyComfortClient.DOrderServiceReference.GetDistributorOrdersByManufacturerRequest();
            inValue.Body = new CozyComfortClient.DOrderServiceReference.GetDistributorOrdersByManufacturerRequestBody();
            inValue.Body.manufacturerId = manufacturerId;
            inValue.Body.statusFilter = statusFilter;
            return ((CozyComfortClient.DOrderServiceReference.DOrderServiceSoap)(this)).GetDistributorOrdersByManufacturerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CozyComfortClient.DOrderServiceReference.GetDistributorOrdersByDistributorResponse CozyComfortClient.DOrderServiceReference.DOrderServiceSoap.GetDistributorOrdersByDistributor(CozyComfortClient.DOrderServiceReference.GetDistributorOrdersByDistributorRequest request) {
            return base.Channel.GetDistributorOrdersByDistributor(request);
        }
        
        public CozyComfortClient.DOrderServiceReference.DOrderDetails[] GetDistributorOrdersByDistributor(int distributorId, string statusFilter) {
            CozyComfortClient.DOrderServiceReference.GetDistributorOrdersByDistributorRequest inValue = new CozyComfortClient.DOrderServiceReference.GetDistributorOrdersByDistributorRequest();
            inValue.Body = new CozyComfortClient.DOrderServiceReference.GetDistributorOrdersByDistributorRequestBody();
            inValue.Body.distributorId = distributorId;
            inValue.Body.statusFilter = statusFilter;
            CozyComfortClient.DOrderServiceReference.GetDistributorOrdersByDistributorResponse retVal = ((CozyComfortClient.DOrderServiceReference.DOrderServiceSoap)(this)).GetDistributorOrdersByDistributor(inValue);
            return retVal.Body.GetDistributorOrdersByDistributorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CozyComfortClient.DOrderServiceReference.GetDistributorOrdersByDistributorResponse> CozyComfortClient.DOrderServiceReference.DOrderServiceSoap.GetDistributorOrdersByDistributorAsync(CozyComfortClient.DOrderServiceReference.GetDistributorOrdersByDistributorRequest request) {
            return base.Channel.GetDistributorOrdersByDistributorAsync(request);
        }
        
        public System.Threading.Tasks.Task<CozyComfortClient.DOrderServiceReference.GetDistributorOrdersByDistributorResponse> GetDistributorOrdersByDistributorAsync(int distributorId, string statusFilter) {
            CozyComfortClient.DOrderServiceReference.GetDistributorOrdersByDistributorRequest inValue = new CozyComfortClient.DOrderServiceReference.GetDistributorOrdersByDistributorRequest();
            inValue.Body = new CozyComfortClient.DOrderServiceReference.GetDistributorOrdersByDistributorRequestBody();
            inValue.Body.distributorId = distributorId;
            inValue.Body.statusFilter = statusFilter;
            return ((CozyComfortClient.DOrderServiceReference.DOrderServiceSoap)(this)).GetDistributorOrdersByDistributorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CozyComfortClient.DOrderServiceReference.GetManufacturersForBlanketResponse CozyComfortClient.DOrderServiceReference.DOrderServiceSoap.GetManufacturersForBlanket(CozyComfortClient.DOrderServiceReference.GetManufacturersForBlanketRequest request) {
            return base.Channel.GetManufacturersForBlanket(request);
        }
        
        public CozyComfortClient.DOrderServiceReference.ManufacturerBlanket[] GetManufacturersForBlanket(int blanketId) {
            CozyComfortClient.DOrderServiceReference.GetManufacturersForBlanketRequest inValue = new CozyComfortClient.DOrderServiceReference.GetManufacturersForBlanketRequest();
            inValue.Body = new CozyComfortClient.DOrderServiceReference.GetManufacturersForBlanketRequestBody();
            inValue.Body.blanketId = blanketId;
            CozyComfortClient.DOrderServiceReference.GetManufacturersForBlanketResponse retVal = ((CozyComfortClient.DOrderServiceReference.DOrderServiceSoap)(this)).GetManufacturersForBlanket(inValue);
            return retVal.Body.GetManufacturersForBlanketResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CozyComfortClient.DOrderServiceReference.GetManufacturersForBlanketResponse> CozyComfortClient.DOrderServiceReference.DOrderServiceSoap.GetManufacturersForBlanketAsync(CozyComfortClient.DOrderServiceReference.GetManufacturersForBlanketRequest request) {
            return base.Channel.GetManufacturersForBlanketAsync(request);
        }
        
        public System.Threading.Tasks.Task<CozyComfortClient.DOrderServiceReference.GetManufacturersForBlanketResponse> GetManufacturersForBlanketAsync(int blanketId) {
            CozyComfortClient.DOrderServiceReference.GetManufacturersForBlanketRequest inValue = new CozyComfortClient.DOrderServiceReference.GetManufacturersForBlanketRequest();
            inValue.Body = new CozyComfortClient.DOrderServiceReference.GetManufacturersForBlanketRequestBody();
            inValue.Body.blanketId = blanketId;
            return ((CozyComfortClient.DOrderServiceReference.DOrderServiceSoap)(this)).GetManufacturersForBlanketAsync(inValue);
        }
    }
}
